
/*
	Programmes to create standard TSPAR library formats
*/

* libname library "W:/Analysis/EOTE_Research/Metadata/Formats";

proc format /* library=library */;

value $ind06d
 'A' = 'Agriculture, Forestry and Fishing'
 'B' = 'Mining'
 'C' = 'Manufacturing'
 'D' = 'Electricity, Gas, Water and Waste Services'
 'E' = 'Construction'
 'F' = 'Wholesale Trade'
 'G' = 'Retail Trade'
 'H' = 'Accommodation and Food Services'
 'I' = 'Transport, Postal and Warehousing'
 'J' = 'Information Media and Telecommunications'
 'K' = 'Financial and Insurance Services'
 'L' = 'Rental, Hiring and Real Estate Services'
 'M' = 'Professional, Scientific and Technical Services'
 'N' = 'Administrative and Support Services'
 'O' = 'Public Administration and Safety'
 'P' = 'Education and Training'
 'Q' = 'Health Care and Social Assistance'
 'R' = 'Arts and Recreation Services'
 'S' = 'Other Services'
 'T' = 'Total'
 Other = 'Not elsewhere classified';

value $ind96d
 ' ' = 'Missing           '
 'A' = 'Ag, Fish, Frst    '
 'B' = 'Mining            '
 'C' = 'Manufacturing     '
 'D' = 'Elec, Gas         '
 'E' = 'Construction      '
 'F' = 'Wholesale Trade   '
 'G' = 'Retail Trade      '
 'H' = 'Accom, Rests      '
 'I' = 'Trans, Storage    '
 'J' = 'Comms             '
 'K' = 'Finance           '
 'L' = 'Business, Property'
 'M' = 'Govt              '
 'N' = 'Education         '
 'O' = 'Health, Community '
 'P' = 'Cultural, Rec     '
 'Q' = 'Personal, Other   ';
 
  value fsze
  0-<6	= ' 1-5 '
  6-<10	= ' 6-9 '
  10-<20 = '10-19'
  20-<50 = '20-49'
  50-<100 = '50-99'
  100-high= '100 +'
  other = 'NEI';

*** AGE ;
***for eote report;
	value agegp
		0-<20    = "  <20"
		20-<25   = "20-24"
	    25-<30   = "25-29"
		30-<35   = "30-34"
	    35-<40   = "35-39"
		40-<45   = "40-44"
	    45-<50   = "45-49"
		50-<55   = "50-54"
	    55-<60   = "55-59"
		60-high  = "60+  "
		other	 = "NEI  ";
***standard age bands;
	value agid
		0-<18	 = "1" 
	    18-<20   = "2"
	    20-<25   = "3"
		25-<40	 = "4"
	    40-high  = "5"
		other    = "9";

	*** age group;
	value $ag
		"1"	 = " under 18" 
	    "2"  = "18-19"
		"3"	 = "20-24"
	    "4"  = "25-39"
	    "5"  = "40+ "
		"9"  = "Unknown";

	***old standard ;
	value ag4id
		0-<18	 = "1" 
	    18-<25   = "2"
	    25-<40   = "3"
	    40-high  = "4"
		other    = "9";
	***old standard age bands ;
	value $ag4gp
		"1"	 = " under 18" 
	    "2"  = "18-24"
	    "3"  = "25-39"
	    "4"  = "40+ "
		other    = "Unknown";

	***old standard age bands ;
	value ag4gp
		0-<18	 = " under 18" 
	    18-<25   = "18-24"
	    25-<40   = "25-39"
	    40-high  = "40+ "
		other    = "Unknown";

	*** AGE - Specific group for pasifika stats - 18 March 2007 *****;
	value ag3id
		0-<18	 = "1" 
	    18-<25   = "2"
	    25-high  = "3"
		other    = "9";

	value $ag3gp
		"1"	 = "Under 18" 
	    "2"  = "18-24"
	    "3"  = "25+"
		"9"  = "Not Stated";

	*** AGE - Specific group for P&T - 30 Sep 2008 *****;
	value ag2id
		0-<25	 = "1" 
	    25-high   = "2"
		other    = "9";

	value $ag2gp
		"1"	 = "Under 25" 
	    "2"  = "25+"
		"9"  = "Not Stated";


	***limited 5 year age bands;
	value ag5gp
		0-<15    = " under 15"
		15-<18   = "15-17"
		18-<20	 = "18-19" 
	    20-<25   = "20-24"
	    25-<30   = "25-29"
		30-<35   = "30-34"
	    35-<40   = "35-39"
		40-high	 = "40 and over"
		other	 = "Unknown";

	***extended 5 year age bands;
	value agx5gp
		0-<15  = " under 15"
		15-<18   = "15-17"
		18-<20	 = "18-19" 
	    20-<25   = "20-24"
	    25-<30   = "25-29"
		30-<35   = "30-34"
	    35-<40   = "35-39"
		40-<45   = "40-44"
	    45-<50   = "45-49"
		50-<55   = "50-54"
	    55-<60   = "55-59"
		60-<65   = "60-64"
		65-high	 = "65 and over"
		other	 = "Unknown";

	***format for fully disaggregated age report;
	value agfgp
		0-<15	=" under 15"
		15		="15"
		16		="16"
		17		="17"
		18		="18"
		19		="19"
		20		="20"
		21		="21"
		22		="22"
		23		="23"
		24		="24"
		25		="25"
		26		="26"
		27		="27"
		28		="28"
		29		="29"
		30-<35   = "30-34"
	    35-<40   = "35-39"
		40-<45   = "40-44"
	    45-<50   = "45-49"
		50-<55   = "50-54"
	    55-<60   = "55-59"
		60-<65   = "60-64"
		65-high	 = "65 and over"
		other	 = "Unknown";

*** ASSIST: CATEGORY OF FEES ASSESSMENT FOR INTERNATIONAL STUDENTS;
	*** standard labels;
	value $assist
		"00" = "Domestic Student"
		"01" = "M.F.A.T. Scholarship"
		"03" = "Full fee paying foreign student"
		"04" = "Exchange Scheme"
		"06" = "Foreign Research based post-graduate"
		"08" = "Diplomatic / Military Staff"
		"09" = "International On-Shore PhD student"
		"12" = "International ITO Off-Job Trainee"
		Other = "ERROR";

*** ATTEND: INTRAMURAL/EXTRAMURAL ATTENDANCE;
	*** standard labels;
	value $attend
		"1"= "Intramural residing in NZ"
		"2"= "Extramural residing in NZ"
		"3"= "Extramural residing overseas"
		"4"= "Intramural residing overseas"
	    Other= "ERROR";

	*** standard grouping: sort order ids;
	value $atid
		"1","4"		=	"1"
		"2","3"		=	"2"
	    Other      =	"9";

	*** standard grouping: labels;
	value $at
		"1"	=	"Intramural"
		"2"	=	"Extramural"
	    "9"	=	"Unknown"
		"T" =   "Total";

*** CITIZEN: COUNTRY OF CITIZENSHIP/ RESIDENTIAL STATUS;
**** Updated with new format $CITIZEN, refer to "I:/Data/TSEC/Formats/Formats_Ref_Tables.sas" for more details - Sathi 25 March 2008 ****;


	****** Format for converting the changes occurred in CITIZEN field from 2007 ******;
	VALUE $citizen_conversion
		"ABW" = "NLD"
		"AIA" = "GBR"
		"ANT" = "NLD"
		"ASM" = "USA"
		"BGB" = "BGD"
		"BMU" = "GBR"
		"BOZ" = "BHI"
		"COK" = "NZL"
		"CSK" = "CZE"
		"CSM" = "SCG"
		"CYM" = "GBR"
		"DDR" = "DEU"
		"ENG" = "GBR"
		"ERN" = "ERI"
		"FLK" = "GBR"
		"FRO" = "DNK"
		"GER" = "DEU"
		"GIB" = "GBR"
		"GJS" = "GBR"
		"GPE" = "FRA"
		"GRL" = "DNK"
		"GTB" = "GBR"
		"GUF" = "FRA"
		"GUM" = "USA"
		"HIL" = "GBR"
		"HKG" = "CHN"
		"IOM" = "GBR"
		"MAC" = "CHN"
		"MCD" = "MKD"
		"MNP" = "USA"
		"MSR" = "FRA"
		"MTQ" = "FRA"
		"NCL" = "FRA"
		"NFK" = "AUS"
		"NID" = "GBR"
		"NIU" = "NZL"
		"PAL" = "PSE"
		"PCN" = "GBR"
		"PGN" = "PNG"
		"PRI" = "USA"
		"PYF" = "FRA"
		"REU" = "FRA"
		"ROM" = "ROU"
		"SGS" = "GBR"
		"SHN" = "GBR"
		"SJM" = "NOR"
		"SKK" = "SVK"
		"SPM" = "FRA"
		"TCA" = "GBR"
		"TKL" = "NZL"
		"TMP" = "TLS"
		"VGB" = "GBR"
		"UMI" = "USA"
		"WAL" = "GBR"
		"WLF" = "FRA"
		"VIR" = "USA"
		"YTD" = "FRA"
		"YUG" = "SCG"
		"XXX" = ""
		"ZAR" = "COD";


******* Old citizen format - no longer used *******;
	value $citizen_old
/*		"ABW"	=	"Aruba"		- included with NLD */
		"AFG"	=	"Afghanistan"
		"AGO"	=	"Angola"
		"AIA"	=	"Anguilla"
		"ALB"	=	"Albania"
		"AND"	=	"Andorra"
/*		"ANT"	=	"Netherlands Antilles"		included with NLD */
		"ARE"	=	"United Arab Emirates"
		"ARG"	=	"Argentina"
		"ARM"	=	"Armenia"
/*		"ASM"	=	"American Samoa"    - included with USA */
		"ATG"	=	"Antigua and Barbuda"
		"AUS"	=	"Australian Citizen"
		"AUT"	=	"Austria"
		"AZE"	=	"Azerbaijan"
		"BDI"	=	"Burundi"
		"BEL"	=	"Belgium"
		"BEN"	=	"Benin"
		"BFA"	=	"Burkina Faso"
		"BGD"	=	"Bangladesh"
		"BGR"	=	"Bulgaria"
		"BHI"	= 	"Bosnia and Herzegovina"
		"BHR"	=	"Bahrain"
		"BHS"	=	"Bahamas"
		"BLR"	=	"Belarus"
		"BLZ"	=	"Belize"
/*		"BMU"	=	"Bermuda"		- included GBR */
		"BOL"	=	"Bolivia"
/*		"BOZ"	=	"Bosnia"		- changed to BHI */
		"BRA"	=	"Brazil"
		"BRB"	=	"Barbados"
		"BRN"	=	"Brunei Darussalam"
		"BTN"	=	"Bhutan"
		"BWA"	=	"Botswana"
		"CAF"	=	"Central African Republic"
		"CAN"	=	"Canada"
		"CHE"	=	"Switzerland"
		"CHL"	=	"Chile"
		"CHN"	=	"China"
		"CIV"	=	"Cote D'Ivoire"
		"CMR"	=	"Cameroon"
		"COG"	=	"Congo"
		"COL"	=	"Colombia"
		"COM"	=	"Comoros"
		"CPV"	=	"Cape Verde"
		"CRI"	=	"Costa Rica"
/*		"CSK"	=	"Czechoslovakia"		- changed to CZE */
		"CUB"	=	"Cuba"
/*		"CYM"	=	"Cayman Islands"		- included with GBR */
		"CYP"	=	"Cyprus"
		"CZE"	= 	"Czech Republic"
		"DEU"	=	"Germany"
		"DJI"	=	"Djibouti"
		"DMA"	=	"Dominica"
		"DNK"	=	"Denmark"
		"DOM"	=	"Dominican Republic"
		"DZA"	=	"Algeria"
		"ECU"	=	"Ecuador"
		"EGY"	=	"Egypt"
/*		"ERN"	=	"Eritrea"		- changed to ERI */
		"ERI"	= 	"Eritrea"
		"ESH"	=	"Spanish Sahara"
		"ESP"	=	"Spain"
		"EST"	=	"Estonia"
		"ETH"	=	"Ethiopia"
		"FIN"	=	"Finland"
		"FJI"	=	"Fiji"
/*		"FLK"	=	"Falkland Islands (Malvinas)"	- included with GBR */
		"FRA"	=	"France"
/*		"FRO"	=	"Faeroe Islands"		- included with DNK */
		"FSM"	=	"Micronesia (FSM)"
		"GAB"	=	"Gabon"
		"GBR"	=	"Great Britain"
		"GEO"	=	"Georgia"
		"GHA"	=	"Ghana"
/*		"GIB"	=	"Gibraltar"				- included with GBR */
		"GIN"	=	"Guinea"
/*		"GJS"	=	"Channel Islands"		- included with GBR */
		"GMB"	=	"Gambia"
		"GNB"	=	"Guinea-Bissau"
		"GNQ"	=	"Equatorial Guinea"
		"GRC"	=	"Greece"
		"GRD"	=	"Grenada"
		"GRL"	=	"Greenland"
		"GTM"	=	"Guatemala"
/*		"GUF"	=	"French Guiana"		- included with GBR */
/*		"GUM"	=	"Guam"				- included with USA */
		"GUY"	=	"Guyana"
/*		"HKG"	=	"Hong Kong"			- included with CHN */
		"HND"	=	"Honduras"
		"HRV"	=	"Croatia"
		"HTI"	=	"Haiti"
		"HUN"	=	"Hungary"
		"IDN"	=	"Indonesia"
		"IND"	=	"India"
/*		"IOM"	=	"Isle Of Man"		- included with GBR */
		"IRL"	=	"Ireland"
		"IRN"	=	"Iran"
		"IRQ"	=	"Iraq"
		"ISL"	=	"Iceland"
		"ISR"	=	"Israel"
		"ITA"	=	"Italy"
		"JAM"	=	"Jamaica"
		"JOR"	=	"Jordan"
		"JPN"	=	"Japan"
		"KAZ"	=	"Kazakhstan"
		"KEN"	=	"Kenya"
		"KGZ"	=	"Kyrgystan"
		"KHM"	=	"Cambodia"
		"KIR"	=	"Kiribati"
		"KNA"	=	"St Kitts-Nevis"
		"KOR"	=	"South Korea"
		"KWT"	=	"Kuwait"
		"LAO"	=	"Laos"
		"LBN"	=	"Lebanon"
		"LBR"	=	"Liberia"
		"LBY"	=	"Libyan Arab Republic"
		"LCA"	=	"St Lucia"
		"LIE"	=	"Liechtenstein"
		"LKA"	=	"Sri Lanka"
		"LSO"	=	"Lesotho"
		"LTU"	=	"Lithuania"
		"LUX"	=	"Luxembourg"
		"LVA"	=	"Latvia"
/*		"MAC"	=	"Macau"				- included with CHN */
		"MAR"	=	"Morocco"
		"MCO"	=	"Monaco"
		"MDA"	=	"Moldavia"
		"MDG"	=	"Madagascar"
		"MDV"	=	"Maldives"
		"MEX"	=	"Mexico"
		"MHL"	=	"Marshall Islands"
		"MKD"	=	"Macedonia"
		"MLI"	=	"Mali"
		"MLT"	=	"Malta"
		"MMR"	=	"Myanmar"
		"MNG"	=	"Mongolia"
		"MNP"	=	"Northern Mariana Islands"
		"MOZ"	=	"Mozambique"
		"MRT"	=	"Mauritania"
		"MSR"	=	"Montserrat"
/*		"MTQ"	=	"Martinique"			- included with FRA */
		"MUS"	=	"Mauritius"
		"MWI"	=	"Malawi"
		"MYS"	=	"Malaysia"
		"NAM"	=	"Namibia"
/*		"NCL"	=	"New Caledonia"			- included with FRA */
		"NER"	=	"Niger"
		"NGA"	=	"Nigeria"
		"NIC"	=	"Nicaragua"
		"NLD"	=	"Netherlands"
		"NOR"	=	"Norway"
		"NPL"	=	"Nepal"
		"NRU"	=	"Nauru"
		"NZL"	=	"New Zealand Citizen"
		"NZP"	=	"NZ Permanent Resident"
		"OMN"	=	"Oman"
		"PAK"	=	"Pakistan"
		"PAL"	=	"Palestinian Territory"
		"PAN"	=	"Panama"
/*		"PCN"	=	"Pitcairn"				- included qith GBR */
		"PER"	=	"Peru"
		"PHL"	=	"Philippines"
		"PLW"	=	"Palau"
		"PNG"	=	"Papua New Guinea"
		"POL"	=	"Poland"
/*		"PRI"	=	"Puerto Rico"			- included with USA */
		"PRK"	=	"North Korea"
		"PRT"	=	"Portugal"
		"PRY"	=	"Paraguay"
		"PSE" 	= 	"Gaza Strip/Palestine/West Bank"
/*		"PYF"	=	"French Polynesia" 		- included with FRA */
		"QAT"	=	"Qatar"
/*		"REU"	=	"Reunion"				- included with FRA */
/*		"ROM"	=	"Romania"				- changed to ROU */
		"ROU"	= 	"Romania"
		"RUS"	=	"Russia"
		"RWA"	=	"Rwanda"
		"SAU"	=	"Saudi Arabia"
		"SCG"	= 	"Serbia and Montenegro"
		"SDN"	=	"Sudan"
		"SEN"	=	"Senegal"
		"SGP"	=	"Singapore"
		"SHN"	=	"St Helena"
/*		"SKK"	=	"Slovakia"				- changed to SVK */
		"SLB"	=	"Solomon Islands"
		"SLE"	=	"Sierra Leone"
		"SLV"	=	"El Salvador"
		"SMR"	=	"San Marino"
		"SOM"	=	"Somalia"
		"SPM"	=	"St Pierre and Miquelon"
		"STP"	=	"Sao Tome and Principe"
		"SUR"	=	"Suriname"
		"SVK"	=	"Slovakia"
		"SVN"	=	"Slovenia"
		"SWE"	=	"Sweden"
		"SWZ"	=	"Swaziland"
		"SYC"	=	"Seychelles"
		"SYR"	=	"Syrian Arab Republic"
/*		"TCA"	=	"Turks and Caicos Islands"		- included with GBR */
		"TCD"	=	"Chad"
		"TGO"	=	"Togo"
		"THA"	=	"Thailand"
		"TJK"	=	"Tajikstan"
		"TKM"	=	"Turkmenistan"
/*		"TMP"	=	"East Timor"		- changed to TLS */
		"TLS"	= 	"Timor-Leste"
		"TON"	=	"Tonga"
		"TTO"	=	"Trinidad and Tobago"
		"TUN"	=	"Tunisia"
		"TUR"	=	"Turkey"
		"TUV"	=	"Tuvalu"
		"TWN"	=	"Taiwan"
		"TZA"	=	"Tanzania"
		"UGA"	=	"Uganda"
		"UKR"	=	"Ukraine"
		"URY"	=	"Uruguay"
		"USA"	=	"United States of America"
		"UZB"	=	"Uzbekstan"
		"VAT"	=	"Vatican City State"
		"VCT"	=	"Saint Vincent and The Grenadines"
		"VEN"	=	"Venezuela"
/*		"VGB"	=	"British Virgin Islands"		- included with GBR */
/*		"VIR"	=	"USA Virgin Islands"			- included with USA */
		"VNM"	=	"Viet Nam"
		"VUT"	=	"Vanuatu"
		"WSM"	=	"Samoa"
		"YEM"	=	"Yemen"
/*		"YUG"	=	"Yugoslavia"					- changed to SCG */
		"ZAF"	=	"South Africa"
		"ZAR"	=	"Zaire"
		"ZMB"	=	"Zambia"
		"ZWE"	=	"Zimbabwe"
		""		=	"Unknown"
		other 	=	"ERROR";

	*** region of citizenship;
	value $citreg 
		"ABW"	=	"Central and South America"
		"AFG"	=	"Asia"
		"AGO"	=	"Africa"
		"AIA"	=	"Central and South America"
		"ALB"	=	"Europe"
		"AND"	=	"Europe"
		"ANT"	=	"Central and South America"
		"ARE"	=	"Middle East"
		"ARG"	=	"Central and South America"
		"ARM"	=	"Europe"
		"ASM"	=	"Pacific"
		"ATG"	=	"Central and South America"
		"AUS"	=	"Pacific"
		"AUT"	=	"Europe"
		"AZE"	=	"Europe"
		"BDI"	=	"Africa"
		"BEL"	=	"Europe"
		"BEN"	=	"Africa"
		"BFA"	=	"Africa"
		"BGD"	=	"Asia"
		"BGR"	=	"Europe"
		"BHR"	=	"Middle East"
		"BHI"	=	"Europe"
		"BHS"	=	"Central and South America"
		"BLR"	=	"Europe"
		"BLZ"	=	"Central and South America"
		"BMU"	=	"Northern America"
		"BOL"	=	"Central and South America"
		"BRA"	=	"Central and South America"
		"BRB"	=	"Central and South America"
		"BRN"	=	"Asia"
		"BTN"	=	"Asia"
		"BWA"	=	"Africa"
		"CAF"	=	"Africa"
		"CAN"	=	"Northern America"
		"CHE"	=	"Europe"
		"CHL"	=	"Central and South America"
		"CHN"	=	"Asia"
		"CIV"	=	"Africa"
		"CMR"	=	"Africa"
		"COD"	=	"Africa"
		"COG"	=	"Africa"
		"COL"	=	"Central and South America"
		"COM"	=	"Africa"
		"CPV"	=	"Middle East"
		"CRI"	=	"Central and South America"
		"CUB"	=	"Central and South America"
		"CYM"	=	"Central and South America"
		"CYP"	=	"Europe"
		"CZE"	=	"Europe"
		"DEU"	=	"Europe"
		"DJI"	=	"Africa"
		"DMA"	=	"Central and South America"
		"DNK"	=	"Europe"
		"DOM"	=	"Central and South America"
		"DZA"	=	"Middle East"
		"ECU"	=	"Central and South America"
		"EGY"	=	"Africa"
		"ERI"	=	"Africa"
		"ESH"	=	"Africa"
		"ESP"	=	"Europe"
		"EST"	=	"Europe"
		"ETH"	=	"Africa"
		"FIN"	=	"Europe"
		"FJI"	=	"Pacific"
		"FLK"	=	"Central and South America"
		"FRA"	=	"Europe"
		"FRO"	=	"Europe"
		"FSM"	=	"Pacific"
		"GAB"	=	"Africa"
		"GBR"	=	"Europe"
		"GEO"	=	"Europe"
		"GHA"	=	"Africa"
		"GIB"	=	"Europe"
		"GIN"	=	"Africa"
		"GJS"	=	"Europe"
		"GMB"	=	"Africa"
		"GNB"	=	"Africa"
		"GNQ"	=	"Africa"
		"GRC"	=	"Europe"
		"GRD"	=	"Central and South America"
		"GRL"	=	"Europe"
		"GTM"	=	"Central and South America"
		"GUF"	=	"Central and South America"
		"GUM"	=	"Pacific"
		"GUY"	=	"Central and South America"
		"HKG"	=	"Asia"
		"HND"	=	"Central and South America"
		"HRV"	=	"Europe"
		"HTI"	=	"Central and South America"
		"HUN"	=	"Europe"
		"IDN"	=	"Asia"
		"IND"	=	"Asia"
		"IOM"	=	"Europe"
		"IRL"	=	"Europe"
		"IRN"	=	"Middle East"
		"IRQ"	=	"Middle East"
		"ISL"	=	"Europe"
		"ISR"	=	"Middle East"
		"ITA"	=	"Europe"
		"JAM"	=	"Central and South America"
		"JOR"	=	"Middle East"
		"JPN"	=	"Asia"
		"KAZ"	=	"Europe"
		"KEN"	=	"Africa"
		"KGZ"	=	"Europe"
		"KHM"	=	"Asia"
		"KIR"	=	"Pacific"
		"KNA"	=	"Central and South America"
		"KOR"	=	"Asia"
		"KWT"	=	"Middle East"
		"LAO"	=	"Asia"
		"LBN"	=	"Middle East"
		"LBR"	=	"Africa"
		"LBY"	=	"Middle East"
		"LCA"	=	"Central and South America"
		"LIE"	=	"Europe"
		"LKA"	=	"Asia"
		"LSO"	=	"Africa"
		"LTU"	=	"Europe"
		"LUX"	=	"Europe"
		"LVA"	=	"Europe"
		"MAC"	=	"Asia"
		"MAR"	=	"Middle East"
		"MCO"	=	"Europe"
		"MDA"	=	"Europe"
		"MDG"	=	"Africa"
		"MDV"	=	"Asia"
		"MEX"	=	"Central and South America"
		"MHL"	=	"Pacific"
		"MKD"	=	"Europe"
		"MLI"	=	"Africa"
		"MLT"	=	"Europe"
		"MMR"	=	"Asia"
		"MNG"	=	"Asia"
		"MNP"	=	"Pacific"
		"MOZ"	=	"Africa"
		"MRT"	=	"Middle East"
		"MSR"	=	"Central and South America"
		"MTQ"	=	"Central and South America"
		"MUS"	=	"Africa"
		"MWI"	=	"Africa"
		"MYS"	=	"Asia"
		"NAM"	=	"Africa"
		"NCL"	=	"Pacific"
		"NER"	=	"Africa"
		"NGA"	=	"Africa"
		"NIC"	=	"Central and South America"
		"NLD"	=	"Europe"
		"NOR"	=	"Europe"
		"NPL"	=	"Asia"
		"NRU"	=	"Pacific"
		"NZL"	=	"Pacific"
		"NZP"	=	"Pacific"
		"OMN"	=	"Middle East"
		"PAK"	=	"Asia"
		"PAL"	=	"Middle East"
		"PAN"	=	"Central and South America"
		"PCN"	=	"Pacific"
		"PER"	=	"Central and South America"
		"PHL"	=	"Asia"
		"PLW"	=	"Pacific"
		"PNG"	=	"Pacific"
		"POL"	=	"Europe"
		"PRI"	=	"Central and South America"
		"PRK"	=	"Asia"
		"PRT"	=	"Europe"
		"PRY"	=	"Central and South America"
		"PYF"	=	"Pacific"
		"QAT"	=	"Middle East"
		"REU"	=	"Africa"
		"ROU"	=	"Europe"
		"RUS"	=	"Europe"
		"RWA"	=	"Africa"
		"SAU"	=	"Middle East"
		"SCG"   =   "Europe"
		"SDN"	=	"Africa"
		"SEN"	=	"Africa"
		"SGP"	=	"Asia"
		"SHN"	=	"Africa"
		"SLB"	=	"Pacific"
		"SLE"	=	"Africa"
		"SLV"	=	"Central and South America"
		"SMR"	=	"Europe"
		"SOM"	=	"Africa"
		"SPM"	=	"Northern America"
		"STP"	=	"Africa"
		"SUR"	=	"Central and South America"
		"SVK"	=	"Europe"
		"SVN"	=	"Europe"
		"SWE"	=	"Europe"
		"SWZ"	=	"Africa"
		"SYC"	=	"Africa"
		"SYR"	=	"Middle East"
		"TCA"	=	"Central and South America"
		"TCD"	=	"Africa"
		"TGO"	=	"Africa"
		"THA"	=	"Asia"
		"TJK"	=	"Europe"
		"TKM"	=	"Europe"
		"TLS"	=	"Asia"
		"TON"	=	"Pacific"
		"TTO"	=	"Central and South America"
		"TUN"	=	"Middle East"
		"TUR"	=	"Middle East"
		"TUV"	=	"Pacific"
		"TWN"	=	"Asia"
		"TZA"	=	"Africa"
		"UGA"	=	"Africa"
		"UKR"	=	"Europe"
		"URY"	=	"Central and South America"
		"USA"	=	"Northern America"
		"UZB"	=	"Europe"
		"VAT"	=	"Europe"
		"VCT"	=	"Central and South America"
		"VEN"	=	"Central and South America"
		"VGB"	=	"Central and South America"
		"VIR"	=	"Central and South America"
		"VNM"	=	"Asia"
		"VUT"	=	"Pacific"
		"WSM"	=	"Pacific"
		"YEM"	=	"Middle East"
		"YUG"	=	"Europe"
		"ZAF"	=	"Africa"
		"ZMB"	=	"Africa"
		"ZWE"	=	"Africa"
		""		=	"Unknown";


****** COMPLETE Course completion code *******;
	value $complete
		"0" = "Still to complete - valid extension or grade not yet available (Register Levels 1-8)"
		"1" = "Still to complete - course end date not yet reached (Register Levels 1-8)"
		"2" = "Completed course successfully"
		"3" = "Completed course unsuccessfully"
		"4" = "Did not complete course"
		"5" = "Practicum to complete - on job training (Register Levels 1-8)"
		"6" = "Yet to complete - Register Levels 9 & 10"
		"7" = "Extension granted or under moderation - Register Levels 9 & 10"
		""  = "Unknown"
		Other = "ERROR";

****** CLASS Course classification code *******;
	value class
		1.0		=	"Agriculture;  Horticulture"
		2.0		=	"Architecture; Quantity Surveying"
		3.0		=	"Arts; Advanced Studies for Teachers; Health Therapies; Humanities; Languages; Social Sciences"
		3.1		=	"Osteopathy"
		4.0		=	"Business; Accountancy; Office Systems/Secretarial; Management"
		5.1		=	"Non-Formal Education"
		5.2		=	"General Education"
		5.3		=	"Short Awards"
		6.0		=	"Computer Science"
		7.0		=	"Dentistry"
		7.1		=	"Dentistry  (Excluding Intermediate) Undergraduate 99"
		7.2		=	"Dentistry  (Excluding Intermediate) Postgraduate 99"
		8.0		=	"Doc Hons A 99"
		9.0		=	"Doc Hons B 99"
		10.0	=	"Doc Hons C 99"
		11.0	=	"Engineering; Technology"
		12.0	=	"Fine Arts; Design"
		13.0	=	"Health Sciences (excluding classifications #07, #15, and #17)"
		13.1	=	"Optometry"
		13.2	=	"Health Sciences Post-entry to Profession 99"
		14.0	=	"Law"
		15.0	=	"Medicine (years 2-3, excluding intermediate/first year)"
		15.1	=	"Medicine (Excluding Intermediate/First Year) Undergraduate 99"
		15.2	=	"Medicine (Excluding Intermediate/First Year) Postgraduate 99"
		16.0	=	"Music And Performing Arts"
		17.0	=	"Health Related Professions"
		17.1	=	"Health Related Professions Pre-entry to profession 99"
		17.2	=	"Health Related Professions  Post-entry to profession 99"
		17.3	=	"Dental Therapy"
		18.0	=	"Science"
		19.1	=	"Teaching: Early Childhood Education Recognised Degree/Diploma of Teaching."
		19.2	=	"Teaching: Primary Recognised Degree/Diploma of Teaching."
		20.0	=	"Teaching: Secondary and Specialist Recognised Degree/Diploma of Teaching."
		21.0	=	"Trades 1: All Trade Courses For Apprentices Under Part III Of The Industry Training Act 1992 And Agricultural, Horticultural, Forestry, And Primary Industry Cadets"
		22.0	=	"Trades 2: All trade courses other than for apprentices under Part III of the Industry Training Act 1992 and Agricultural, Horticultural, Forestry, and Primary Industry Cadets."
		23.0	=	"Veterinary (Excluding Intermediate)"
		23.1	=	"Veterinary (Excluding Intermediate)  (For Bvsc) Undergraduate 99"
		23.2	=	"Veterinary (Excluding Intermediate)  (Postgraduate Study From Bvsc Qualification) Postgraduate"
		23.3	=	"Veterinary Science Undergraduate (years 3, 4 & 5)"
		24.0	=	"Nursing"
		25.0	=	"Medical Imaging"
		26.0	=	"Midwifery (1 Year)"
		27.0	=	"Midwifery (3 Year)"
		28.0	=	"Occupational Therapy"
		29.0	=	"Physiotherapy"
		30.0	=	"Medical Radiation Therapy (MRT)"
		31.0	=	"Pharmacy Professionals"
		32.0	=	"Speech And Language Therapy"
		33.0	=	"Medical Laboratory Science (MLS)"
		34.0	=	"Clinical Psychology"
		35.0	=	"Audiology"
		36.0	=	"Dietetics"
		37.0	=	"Medical Undergraduate (Years 4, 5 & 6 )"
		38.0	=	"Foreign-Going Nautical"
		39.0	=	"Specialist Large Animal Science"
		39.1	=	"Specialist Large Animal Science Undergraduate 99"
		39.2	=	"Specialist Large Animal Science Postgraduate 99"
		Other	=	"ERROR";


*** DECILE ;
	*** standard labels;
	value $decile 
		"01"	=	"Decile 1"
		"02"	=	"Decile 2"
		"03"	=	"Decile 3"
		"04"	=	"Decile 4"
		"05"	=	"Decile 5"
		"06"	=	"Decile 6"
		"07"	=	"Decile 7"
		"08"	=	"Decile 8"
		"09"	=	"Decile 9"
		"10"	=	"Decile 10"
		""		=	"Unknown"
		Other   =	"ERROR";

	***sort order id for standard decile band groupings;
	value $dbid 
		"01"	=	"1"
		"02"	=	"1"
		"03"	=	"1"
		"04"	=	"2"
		"05"	=	"2"
		"06"	=	"2"
		"07"	=	"2"
		"08"	=	"3"
		"09"	=	"3"
		"10"	=	"3"
		other	=	"9";

	***standard decile band groupings;
	value $db 
		"1"	=	"Deciles 1-3"
		"2"	=	"Deciles 4-7"
		"3"	=	"Deciles 8-10"
		"9"	=	"Unknown"
		"T"	=	"Total";

*** DISABLE: DISABILITY ;
	*** standard labels;
	value $disable
		"1"	= "No Disability identified"
		"2" = "Disability identified"
		""	= "Unknown"
		"T" = "Total"
		other = "ERROR";

*** DIS_ACCESS: DISABILITY SERVICES ACCESSED ;
	*** standard labels;
	value $dis_access
		"1" = "Disability services accessed"
		"2" = "Disability services not accessed"
		""  = "Unknown"
		"T" = "Total"
		Other = "ERROR";

*** EFTS STUDY LOAD ;
	***standard efts grouping: sort order ids;
	value elid
		0.025 - <0.20	=	"1"
		0.20 - <0.40	=	"2"
		0.40 - <0.60	=	"3"
		0.60 - <0.80	=	"4"
		0.80 -  high	=	"5"
		other			=   "9";

	***standard efts grouping: labels;
	value $el
		"1"	=	"0.03-0.19"
		"2"	=	"0.20-0.39"
		"3"	=	"0.40-0.59"
		"4"	=	"0.60-0.79"
		"5"	=	"0.80 plus"
		" "	=   "Unknown  ";

	***standard efts years grouping: sort order ids;
	value eyid
		0.03 - 0.5	=	"01"
		>0.5 - 1.0	=	"02"
		>1.0 - 1.5	=	"03"
		>1.5 - 2.0	=	"04"
		>2.0 - 2.5	=	"05"
		>2.5 - 3.0	=	"06"
		>3.0 - 3.5	=	"07"
		>3.5 - 4.0	=	"08"
		>4.0 - 4.5	=	"09"
		>4.5 - 5.0	=	"10"
		>5.0		=	"11"
		other		=   "99";

	***standard efts years grouping: labels;
	value $ey
		"01"	=	">0 - 0.5"
		"02"	=	">0.5-1.0"
		"03"	=	">1.0-1.5"
		"04"	=	">2.0-2.5"
		"05"	=	">2.5-3.0"
		"06"	=	">3.0-3.5"
		"07"	=	">3.5-4.0"
		"08"	=	">4.0-4.5"
		"09"	=	">4.5-5.0"
		"10"	=	"5.0 plus"
		"99"	=   "Unknown ";

*** ETHNIC, ETHNIC1-3: ETHNIC GROUP ;
	****** Standard labels for Ethnicity: ETHNIC1-ETHNIC3, new 3 digit codes ******;
	value $ethnic
		"100" = "European NFD/Pakeha"		/* Non-stanadrd - Used for those coded to European/Pakeha prior to 2007 data*/
		"111" = "NZ European/Pakeha"
		"121" = "British/Irish"
		"122" = "Dutch"
		"123" = "Greek"
		"124" = "Polish"
		"125" = "South Slav"
		"126" = "Italian"
		"127" = "German"
		"128" = "Australian"
		"129" = "Other European"
		"211" = "New Zealand Maori"
		"311" = "Samoan"
		"321" = "Cook Island Maori"
		"331" = "Tongan"
		"341" = "Niuean"
		"351" = "Tokelauan"
		"361" = "Fijian"
		"371" = "Other Pacific Island Groups"
		"400" = "Other Asian NFD"			/* Non-standard - Related to Other Asian group prior to 2007 data*/
		"411" = "Filipino"
		"412" = "Cambodian"
		"413" = "Vietnamese"
		"414" =	"Other Southeast Asian"
		"421" = "Chinese"
		"431" = "Indian"
		"441" = "Sri Lankan"
		"442" = "Japanese"
		"443" = "Korean"
		"444" = "Other Asian"
		"500" = "Other NFD"				/* Related to Other group prior to 2007 data*/
		"511" = "Middle Eastern"
		"521" = "Latin American"
		"531" = "African"
		"611" = "Other"
		"" = 	"Not Stated"
		Other = "ERROR";

		**** Old ethnic groups;
	value $ethnic_old
		"01" =	"European"
		"20" =	"Maori"
		"31" =	"Samoan"
		"32" =	"Cook Island" 
		"33" =	"Tongan"
		"34" =	"Niuean"
		"35" =	"Tokelauan"
		"36" =	"Fijian"
		"37" =	"Other Pasifika Groups"
		"51" =	"Chinese"
		"52" =	"Indian"
		"68" =	"Other Asian"
		"89" =	"Other"
		"" =	"Unknown"
		"T"  =  "Total"
		Other= 	"ERROR";

	****** Converting 2-digit ethnicity codes to 3-digit codes (from 2007) *******;
	value	$ethnic_conversion
		"01" = "100"
		"20" = "211"
		"31" = "311"
		"32" = "321"
		"33" = "331"
		"34" = "341"
		"35" = "351"
		"36" = "361"
		"37" = "371"
		"51" = "421"
		"52" = "431"
		"68" = "400"
		"89" = "500"
		"99" = "";

	****** Grouping the new 3 digit ethnic codes in the old level 1 output classification  ******;
	value $egidold
		"100", "111", "121"-"129" 						= "1" 
		"211"											= "2" 
		"311", "321", "331", "341", "351", "361", "371"	= "3" 
		"400", "411"-"414", "421", "431", "441"-"444"	= "4" 
		"500", "511", "521", "531", "611"				= "5" 
		"999",""										= "9";

	****** Grouping the new 3 digit ethnic codes in the new level 1 output classification  ******;
	value $egid_new
		"111", "121"-"129" 								= "1" 
		"211"											= "2" 
		"311", "321", "331", "341", "351", "361", "371"	= "3" 
		"411"-"414", "421", "431", "441"-"444"			= "4" 
		"511", "521", "531"								= "5" 
		"611"											= "6"
		"999",""										= "9";

	*** NOTE: not possible to convert old codes to new level 1 output classification ;

	****** Ethnicity Labels for new 3 digit codes - new level 1 output classification ******;
	value $eg_new
		"1" = "European"
		"2" = "Maori"
		"3" = "Pasifika"
		"4" = "Asian"
		"5" = "Middle Eastern/Latin American/African"
		"6" = "Other"
		"9" = "Unknown"
		"T" = "Total";

	value $egold
		"1" 		= "European"
		"2" 		= "Maori"
		"3" 		= "Pasifika"
		"4" 		= "Asian"
		"5", "6"	= "Other"
		"9" 		= "Unknown"
		"T" 		= "Total";


****** Exempt Indicator for Courses *******;
	VALUE $exempt_indicator
		"1" = "Course has been granted exemption from FCCM"
		"2" = "Course has no exemption from FCCM"
		" " = "Not Specified"
		Other = "ERROR";


*** FINISH: EXPECTATION TO COMPLETE A QUALIFICATION THIS YEAR ;
	*** standard labels;
	value $finish
		"Y"	=	"Yes"
		"N"	=	"No"
		"" =	"Unknown"
		Other = "ERROR";

*** FUNDING: SOURCE OF FUNDING ;
	*** standard labels;
	value $funding
		"01" = "Student component"
		"02" = "Full fee paying foreign students"
		"03" = "Full fee paying domestic students"
		"04" = "TEC - Supplementary Grants/Fund"
		"05" = "STAR funded student"
		"06" = "Training Opportunities"
		"07" = "Youth Training"
		"08" = "Skill Enhancement"
		"09" = "Prison Education"
		"10" = "Ministry of Health"
		"11" = "ITO off-the-job training"
		"12" = "Other contracts"
		"13" = "English for Migrants (TEC Only)"
		"14" = "Primary Pre-service Teacher Education Contracts"
		"15" = "Secondary Pre-service Teacher Education Contracts"
		"16" = "Youth Action Training Programme (DWI)"
		"20" = "Ministry of Foreign Affairs and Trade sponsored student"
		"21" = "ITO off-the-job training foreign student"
		""   = "Unknown"
		other = "ERROR";

*** GENDER ;
	*** standard labels;
	value $gender
		"M" = "Male"
		"F"	= "Female"
		"T" = "Total"
		Other = "ERROR";

*** INSTIT: INSTITUTION ;
***** New format is generated, refer to "I:/Data/TSEC/Formats/Formats_Ref_Tables.sas" for more details - Sathi 25 March 2008 *****;

*** ISCED LEVEL ;
	*** standard labels;
	value $isced_level
		"3A"	=	"Isced level 3A"
		"3B"	=	"Isced level 3B"
		"3C"	=	"Isced level 3C"
		"4A"	=	"Isced level 4A"
		"4B"	=	"Isced level 4B"
		"4C"	=	"Isced level 4C"
		"5A" 	=	"Isced level 5A"
		"5B"	=	"Isced level 5B"
		"6"		 =	"Isced level 6"
		"9"		=	"Non-formal"
		Other = "ERROR";

*** ISCED SUBSEQUENT DESTINATION ;
	*** standard labels;
	value $isced_dest
		"A"	=	"Designed to lead to higher academically-based education"
		"B"	=	"Designed to lead to higher vocationally-based education"
		"C"	=	"Designed to lead direct to the labour market"
		""  =	"Not applicable or Unknown"
		Other = "ERROR";

*** Isced level and destination - for converting QACC to ISCED level ;
	value $isced_conversion
	"01", "10" 				= "6 "
	"11","12","13","14",		
	"20","21","25"			= "5A"
	"30"-"35"				= "5B"
	"36"-"37","43"			= "4 "
	"40","41","46","60","98"= "3 "
	other  					= "E "; /* includes non-formal 90,97,99: 96 (star) */

****** ISCED to Level Conversion *******;
	value $ISCED_to_Level	"3"  = "Level 1-3 Certificate"
							"4"  = "Level 4 Certificate"
							"5B" = "Level 5-7 Diploma"
							"5A" = "Level 7-9 Bachelors/honours/Masters"
							"6"  = "Level 10 Doctorates";

*** INTERNET ;
	*** standard labels;
	value $internet
		"1"	=	"No Access"
		"2"	=	"Web-supported"
		"3"	=	"Web-enhanced"
		"4"	=	"Web-based"
		""  =	"Unknown"
		Other = "ERROR";

*** IWI ;
***** Format $IWI updated, refer to "I:/Data/TSEC/Formats/Formats_Ref_Tables.sas" for more details - Sathi 25 March 2008 ******;


*** L_NATURE: LET-BASED NATURE OF ATTENDANCE ;
	*** standard labels;
	value $l_nature
		"F"	=	"Full-time"
		"P"	=	"Part-time"
	    Other=	"ERROR";	

	***LET  ;
	value let(fuzz=0)
		1 = "0.025"
		2 = "0.05"
		3 = "0.075"
		4 = "0.1"
		5 = "0.125"
		6 = "0.15"
		7 = "0.175"
		8 = "0.2"
		9 = "0.225"
		10 = "0.25"
		11 = "0.275"
		12 - 15 = "0.3"
		16 - 19 = "0.4"
		20 = "0.5"
		21 = "0.525"
		22 = "0.55"
		23 = "0.575"
		24 = "0.6"
		25 = "0.625"
		26 = "0.65"
		27 = "0.675"
		28 = "0.7"
		29 = "0.725"
		30 = "0.75"
		31 = "0.775"
		32 - 52 = "0.8"
		53 - HIGH = "1.000";

	***standard 8-level sort order id grouping of qacc to qualification level;
	value $lv8id
		"40"-"41","46", "60", "96", "98"	="1"
		"36"-"37","43"		="2"	
		"30"-"35"			="3"
		"20","25"			="4"
		"21"				="5"
		"12"-"14"			="6"
		"11"				="7"
		"01","10"			="8"
		"90", "97", "99"	="9"
		Other				="E";

	***standard 8-level grouping labels;
	value $lv8d
		"1"		=	"Level 1-3 certificates"
		"2"     =	"Level 4 certificates"
		"3"     =	"Diplomas"		
		"4"     =	"Bachelors"
		"5"     =	"Level 7 graduate certs/dips"
		"6"		=	"Level 8 honours/postgrad certs/dips"
	    "7"     =	"Masters"
		"8"		=	"Doctorates"
		"9"		=	"Non formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 

		***old standard 7-level sort order id grouping of qacc to qualification level;
	value $lv7id
		"40"-"41","46", "60", "96", "98"	="1"
		"36"-"37","43"		="2"	
		"30"-"35"			="3"
		"20"-"25"			="4"
		"12"-"14"			="5"
		"11"				="6"
		"01","10"			="7"
		"90", "97", "99"	="9"
		Other				="E";

	***old standard 7-level grouping labels;
	value $lv7d
		"1"		=	"Level 1-3 certificate"
		"2"     =	"Level 4 certificate"
		"3"     =	"Level 5-7 diploma"		
		"4"     =	"Level 7 bachelors"
		"5"		=	"Level 8 honours/postgrad cert/dip"
	    "6"     =	"Level 9 masters"
		"7"		=	"Level 10 doctorates"
		"9"		=	"Non formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 

	***alternate level 7 labels for pasifika tables: (DE);
	value $lv7d_P
		"1"		=	"Certificates 1-3"
		"2"     =	"Certificates 4"
		"3"     =	"Diplomas 5-7"		
		"4"     =	"Bachelors"
		"5"		=	"Honours, postgrad cert/dip"
	    "6"     =	"Masters"
		"7"		=	"Doctorates"
		"9"		=	"Non Formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 

*** 6-level sort order id grouping of qacc to qualification level;
	value $lv6id
		"40"-"41","46", "60", "96", "98",		
		"36"-"37","43"		="1"	
		"30"-"35"			="2"	
		"20"-"25"			="3"
		"12"-"14"			="4"
		"11"				="5"
		"01","10"			="6"
		"90", "97", "99"	="9"
		Other				="E";

*** 6-level grouping : labels;
	value $lv6d
		"1"		=	"Certificate"
		"2"     =	"Diploma"		
		"3"     =	"Bachelors"
		"4"		=	"Honours/Postgrad cert/dip"
	    "5"     =	"Masters"
		"6"		=	"Doctorate"
		"9"		=	"Non Formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 


	***standard 5-level sort order id grouping of qacc to qualification level;
	value $lv5id
		"40"-"41","46", "60", "96", "98"	="1"	
		"36"-"37","43"		="2"	
		"30"-"35"			="3"	
		"20"-"25"			="4"
		"12"-"14", "11", "01", "10"			="5"
		"90", "97", "99"	="9"
		Other				="E";

	***standard 5 grouping : labels;
	value $lv5d
		"1"		=	"Certificates 1-3"
		"2"     =	"Certificates 4"
		"3"     =	"Diplomas 5-7"	
		"4"     =	"Bachelors"
		"5" 	=	"Postgraduate"
		"9"		=	"Non Formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 

	***standard 4-level sort order id grouping of qacc to qualification level - levels 1-3, level 4-7 grouped;
	value $lv4id
		"40"-"41","46", "60", "96", "98"	=	"1"	
		"36"-"37","43","30"-"35"			=	"2"	
		"20"-"25"							=	"3"
		"01","10"-"14"						=	"4"
		"90", "97", "99"					=	"5"
		Other								=	"E";

	****** standard 4-level grouping : labels ******;
 	VALUE $lvl4d	"1" = "Upper secondary"
					"2" = "Post-secondary non-degree"
					"3" = "Bachelors"
					"4" = "Post-graduate"
					"5" = "Non-formal"
					"T" = "Total"
					"E" = "ERROR";

	***alternate 4-level grouping - levels 1-4 grouped, levels 5-7 grouped;
	value $lv4ida
		"36", "37", "43", "40", "41", "46", "60", "96", "98"	="1"
		"30"-"35"												="2"
		"20"-"25"												="3"
		"01","10"-"14"											="4"
		"90", "97", "99"										="9"
		Other 													="E";

	***alternate 4-level grouping : labels;
	value $lv4da
		"1"		=	"Certificate"
		"2"     =	"Diploma"
		"3"     =	"Bachelors"
		"4"		=	"Postgraduate"
		"9"		=	"Non Formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 

	***standard 3-level grouping : sort order ids;
	value $lv3id
		"30"-"37","40"-"41","43","46","60","96","98"	="1"
		"20"-"25"										="2"
		"01","10"-"14"									="3"
		"90","97","99"									="9"
		Other											="E";

	***standard 3-level grouping : labels;
	value $lv3d
		"1"		=	"Sub-degree"
		"2"     =	"Degree"
		"3"     =	"Postgraduate"
		"9"		=	"Non Formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 


	***3-level grouping used for profile and trends;
	value $lvptid
		"40", "41", "46", "60", "96", "98"	="1"
		"30"-"37", "43"						="2"
		"01","10"-"25"						="3"
		"90", "97", "99"					="9"
		Other 								="E";

	***standard 2-level grouping;
	value $lv2id
		"40"-"41","46", "60", "96", "98"	="1"	
		"36"-"37","43",	"30"-"35",
		"20"-"25", "12"-"14", "11", 
		"01","10" 							="2"
		"90", "97", "99"					="9"
		Other								="E";

	***standard 2-level grouping : labels;
	value $lv2d
		"1"		=	"Level 1-3 Certificate"
		"2"     =	"Level 4 or higher"
		"9"     =	"Non Formal"
		"E"		=	"ERROR"
		"T" 	=	"Total"; 


	****** mandatory_course ******;
	VALUE	$mandatory_course
		"Y"	= "Yes"
		"N" = "No"
		"U","" = "Unknown"
		Other = "ERROR";

*** MAIN_1-MAIN_3: QUALIFICATION COMPLETION MAJOR SUBJECT ;
	*** standard labels;
	value $main
		"ANSC" =	"Animal Science"
		"BCHM" =	"Biochemistry"
		"BIOL" =	"Biology/Biological Science"
		"BIOT" =	"Biotechnology"
		"BOTY" =	"Botany/Plant Science"
		"CHEM" =	"Chemistry"
		"EASC" =	"Earth Sciences"
		"ECOL" =	"Ecology"
		"FINM" =	"Financial Mathematics"
		"FOOD" =	"Food Science/Technology"
		"SCIE" =	"General Science"
		"GEOL" =	"Geology"
		"HUMB" =	"Human Biology"
		"MASC" =	"Marine Science/Oceanography"
		"MATH" =	"Mathematics"
		"MICR" =	"Microbiology"
		"OPRE" =	"Operations Research"
		"PHYS" =	"Physics/Physical Science"
		"STAT" =	"Statistics"
		"TECH" =	"Technology/Applied Science"
		"ZOOL" =	"Zoology"
		"COMP" =	"Computer Science"
		"INFO" =	"Information Systems/Science"
		"CLTX" =	"Clothing & Textiles"
		"DEST" =	"Design & Technology"
		"ENGN" =	"Engineering (General)"
		"ENGC" =	"Computer Engineering"
		"ENCH" =	"Chemical Engineering"
		"ENCV" =	"Civil Engineering"
		"ENGE" =	"Electrical /Electronics Engineering"
		"ENGV" =	"Environmental Engineering"
		"ENGM" =	"Mechanical Engineering"
		"ENME" =	"Mineral/Mining Engineering"
		"MANU" =	"Manufacturing & Industrial"
		"MLWK" =	"Metalwork"
		"QUAL" =	"Quality Studies"
		"SURV" =	"Surveying"
		"WOOD" =	"Woodwork"
		"WKTE" =	"Workshop Technology"
		"ARCH" =	"Architecture"
		"RESM" =	"Resource Management"
		"AGCO" =	"Agriculture Business/Commerce"
		"AGHO" =	"Agriculture & Horticulture"
		"AGRI" =	"Agriculture/ Agricultural Science"
		"ANHL" =	"Animal Health"
		"ENVI" =	"Environmental Science"
		"FORE" =	"Forestry"
		"HORT" =	"Horticulture"
		"SOIL  " =	"Soil Science"
		"DENT" =	"Dentistry"
		"MEDI" =	"General Medicine/Surgery"
		"HEED" =	"Health Education/Science"
		"HEAL" =	"Health Management"
		"MIDW" =	"Midwifery"
		"NURS" =	"Nursing"
		"NUTR" =	"Nutrition/Nutritional Science"
		"OPTY" =	"Optometry"
		"PHMY" =	"Pharmacy/Pharmacology"
		"PHYG" =	"Physiology/Anatomy"
		"SPMD" =	"Specialist Medicine/Surgery"
		"SPSC" =	"Sports Science"
		"TUTR" =	"Adult Tutoring"
		"ASTU" =	"Advanced Studies for Teachers"
		"ECET" =	"Early Childhood Teaching"
		"EDUC" =	"Education/Educational Studies"
		"EDPY" =	"Educational Psychology"
		"TESL" =	"English as Second Language Teaching"
		"PHED" =	"Physical Education"
		"PRIM" =	"Primary School Teaching"
		"REMM" =	"Remedial Teaching"
		"SPEC" =	"Special Education Teaching"
		"TRDV" =	"Training & Development"
		"ACCY" =	"Accountancy"
		"BUAD" =	"Business Administration"
		"BUSS" =	"Business Studies"
		"COML" =	"Commercial Law"
		"ECHI" =	"Economic History"
		"ECON" =	"Economics"
		"FINA" =	"Finance/Financial Management"
		"HURE" =	"Human Resource Management"
		"INRC" =	"Industrial Relations"
		"MGMT" =	"Management"
		"MKTG" =	"Marketing"
		"OFSE" =	"Office/Secretarial Systems"
		"PRMT" =	"Property Management"
		"PUBL" =	"Public Relations"
		"SHOR" =	"Shorthand"
		"SHTY" =	"Shorthand Typing"
		"TYPE" =	"Typing & Wordprocessing"
		"VALU" =	"Valuation"
		"ANTH" =	"Anthropology"
		"ARHY" =	"Archaeology"
		"ARTH" =	"Art History"
		"CLAS" =	"Classical Studies"
		"COMM" =	"Communication Studies"
		"COSW" =	"Community Social Services"
		"COUN" =	"Counselling"
		"CRIM" =	"Criminology"
		"DEMY" =	"Demography"
		"DEVE" =	"Development Studies"
		"ESOL" =	"English (as a Second Language)"
		"ENGL" =	"English Literature/Language"
		"GEOG" =	"Geography"
		"HIST" =	"History"
		"HOEC" =	"Home Economics"
		"INTR" =	"International Relations"
		"JOUR" =	"Journalism/Media Studies"
		"LAWS" =	"Law"
		"LIBR" =	"Librarianship"
		"LING" =	"Linguistics"
		"MAST" =	"Maori Studies"
		"PHIL" =	"Philosophy"
		"POLS" =	"Politics/Political Science"
		"PSYC" =	"Psychology"
		"RELI" =	"Religion/Religious Studies"
		"POLY" =	"Social & Public Policy/Admin"
		"SSRE" =	"Social Science Research"
		"SOST" =	"Social Studies"
		"SOWK" =	"Social Work"
		"SOSC" =	"Sociology"
		"SPOR" =	"Sport & Recreation"
		"THEO" =	"Theology"
		"WISC" =	"Womens Studies"
		"NZST" =	"New Zealand Studies"
		"PIST" =	"Pacific Studies"
		"ASST" =	"Asian Studies"
		"AMST" =	"American Studies"
		"EUST" =	"European Studies"
		"AFST" =	"African Studies"
		"ASIA" =	"Asian Languages"
		"CHIN" =	"Chinese"
		"COOK" =	"Cook Island Maori"
		"DUTC" =	"Dutch"
		"FREN" =	"French"
		"GERM" =	"German"
		"GREE" =	"Greek"
		"HEBR" =	"Hebrew"
		"INDO" =	"Indonesian"
		"ITAL" =	"Italian"
		"JAPA" =	"Japanese"
		"KORE" =	"Korean"
		"LATI" =	"Latin"
		"MAOR" =	"Maori (Te Reo)"
		"NIUE" =	"Niuean"
		"RUSS" =	"Russian"
		"SAMO" =	"Samoan"
		"SPAN" =	"Spanish"
		"TOKE" =	"Tokelauan"
		"TONG" =	"Tongan"
		"ARTS" =	"Art & Design"
		"DRAM" =	"Drama/Dance"
		"FILM" =	"Film & Theatre Studies"
		"GRAP" =	"Graphics & Design"
		"MUSI" =	"Music"
		"AVST" =	"Aviation Studies"
		"REAL" =	"Real Estate"
		"TOUR" =	"Tourism"
		"" =		"Unknown"
		Other  =	"ERROR";


*** NZRES: DOMESTIC OR INTERNATIONAL;
	*** standard labels;
	value $nzres
		"1"	=	"Domestic"
		"0"	=	"International"
		"T" = 	"Total"
		Other = "ERROR";

*** NZSCED: NZSCED FIELD OF STUDY;
	*** standard labels for nzsced at detail level - last updated 24/7/2006;
	value $nzsced
		"010100" = "Mathematical Sciences nfd"
		"010101" = "Mathematics"
		"010103" = "Statistics"
		"010199" = "Mathematical Sciences nec"
		"010300" = "Physics and Astronomy nfd"
		"010301" = "Physics"
		"010303" = "Astronomy"
		"010500" = "Chemical Sciences nfd"
		"010501" = "Organic Chemistry"
		"010503" = "Inorganic Chemistry"
		"010599" = "Chemical Sciences nec"
		"010700" = "Earth Sciences nfd"
		"010701" = "Atmospheric Sciences"
		"010703" = "Geology"
		"010705" = "Geophysics"
		"010707" = "Geochemistry"
		"010709" = "Soil Science"
		"010711" = "Hydrology"
		"010713" = "Oceanography"
		"010799" = "Earth Sciences nec"
		"010900" = "Biological Sciences nfd"
		"010901" = "Biochemistry and Cell Biology"
		"010903" = "Botany"
		"010905" = "Ecology and Evolution"
		"010907" = "Marine Science"
		"010909" = "Genetics"
		"010911" = "Microbiology"
		"010913" = "Human Biology"
		"010915" = "Zoology"
		"010916" = "Neuroscience"
		"010999" = "Biological Sciences nec"
		"019900" = "Other Natural and Physical Sciences nfd"
		"019901" = "Medical Science"
		"019903" = "Forensic Science"
		"019905" = "Food Science and Biotechnology"
		"019907" = "Pharmacology"
		"019909" = "Laboratory Technology"
		"019999" = "Natural and Physical Sciences nec"
		"020100" = "Computer Science nfd"
		"020101" = "Formal Language Theory"
		"020103" = "Programming"
		"020105" = "Computational Theory"
		"020107" = "Compiler Construction"
		"020109" = "Algorithms"
		"020111" = "Data Structures"
		"020113" = "Networks and Communications"
		"020115" = "Computer Graphics"
		"020117" = "Operating Systems"
		"020119" = "Artificial Intelligence"
		"020199" = "Computer Science nec"
		"020300" = "Information Systems nfd"
		"020301" = "Conceptual Modelling"
		"020303" = "Database Management"
		"020305" = "Systems Analysis and Design"
		"020307" = "Decision Support Systems"
		"020399" = "Information Systems nec"
		"029900" = "Other Information Technology nfd"
		"029901" = "Security Science"
		"029999" = "Information Technology nec"
		"030100" = "Manufacturing, Engineering and Technology nfd"
		"030101" = "Manufacturing Engineering"
		"030103" = "Printing"
		"030105" = "Textile Making"
		"030107" = "Garment Making"
		"030108" = "Plastics Processing Technology"
		"030109" = "Footwear Making"
		"030111" = "Wood Machining and Turning"
		"030113" = "Cabinet Making"
		"030115" = "Furniture Upholstery and Renovation"
		"030117" = "Furniture Polishing"
		"030199" = "Manufacturing Engineering and Technology nec."
		"030300" = "Process and Resources Engineering nfd"
		"030301" = "Chemical Engineering"
		"030303" = "Mining and Resources Engineering"
		"030304" = "Wood Based Manufacturing"
		"030305" = "Materials Engineering"
		"030306" = "Ceramics, Industrial Glass and Rubber Manufacturing"
		"030307" = "Food (excluding Seafood) Processing Technology"
		"030308" = "Seafood Processing"
		"030399" = "Process and Resources Engineering nec"
		"030500" = "Automotive Engineering and Technology nfd"
		"030501" = "Automotive Engineering"
		"030503" = "Vehicle Mechanics"
		"030505" = "Automotive Electrics and Electronics"
		"030507" = "Automotive Vehicle  Refinishing"
		"030509" = "Automotive Body Construction"
		"030511" = "Panel Beating"
		"030513" = "Upholstery and Vehicle Trimming"
		"030515" = "Automotive Vehicle Operations"
		"030599" = "Automotive Engineering and Technology nec"
		"030700" = "Mechanical and Industrial Engineering and Technology nfd"
		"030701" = "Mechanical Engineering"
		"030703" = "Industrial Engineering"
		"030705" = "Toolmaking"
		"030707" = "Metal Fitting, Turning and Machining"
		"030709" = "Sheetmetal Working"
		"030711" = "Boiler-making and Welding"
		"030713" = "Metal Casting and Pattern Making"
		"030715" = "Precision Metalworking"
		"030717" = "Plant and Machine Operations"
		"030799" = "Mechanical and Industrial Engineering & Technology nec"
		"030900" = "Civil Engineering nfd"
		"030901" = "Construction Engineering"
		"030903" = "Structural Engineering"
		"030905" = "Building Services Engineering"
		"030907" = "Water and Sanitary Engineering"
		"030909" = "Transport Engineering"
		"030910" = "Road Construction"
		"030911" = "Geotechnical Engineering"
		"030913" = "Ocean Engineering"
		"030999" = "Civil Engineering nec"
		"031100" = "Geomatic Engineering nfd"
		"031101" = "Surveying"
		"031103" = "Mapping Science"
		"031199" = "Geomatic Engineering nec"
		"031300" = "Electrical and Electronic Engineering and Technology nfd"
		"031301" = "Electrical Engineering"
		"031303" = "Electronic Engineering"
		"031305" = "Computer Engineering"
		"031307" = "Communications Technologies"
		"031309" = "Communications Equipment Installation and Maintenance"
		"031311" = "Power Line Installation and Maintenance"
		"031313" = "Electrical Fitting, Electrical Mechanics"
		"031315" = "Refrigeration, Heating and Air Conditioning"
		"031317" = "Electronic Equipment Servicing"
		"031399" = "Electrical and Electronic Engineering  and Technology nec"
		"031500" = "Aerospace Engineering and Technology nfd"
		"031501" = "Aerospace Engineering"
		"031503" = "Aircraft Maintenance Engineering"
		"031505" = "Aircraft Operation"
		"031507" = "Air Traffic Control"
		"031599" = "Aerospace Engineering and Technology nec"
		"031700" = "Maritime Engineering and Technology nfd"
		"031701" = "Maritime Engineering"
		"031703" = "Marine Construction"
		"031705" = "Marine Craft Operation"
		"031799" = "Maritime Engineering and Technology nec"
		"039900" = "Other Engineering and Related Technologies nfd"
		"039901" = "Environmental Engineering"
		"039902" = "Orthotics and Prosthetics"
		"039903" = "Biomedical Engineering"
		"039905" = "Fire Technology and Rescue Services"
		"039907" = "Rail Operations"
		"039909" = "Cleaning"
		"039999" = "Engineering and Related Technologies  nec"
		"040100" = "Architecture and Urban Environment nfd"
		"040101" = "Architecture"
		"040103" = "Urban Design and Regional Planning"
		"040105" = "Landscape Architecture"
		"040107" = "Interior and Environmental Design"
		"040199" = "Architecture and Urban Environment nec"
		"040300" = "Building nfd"
		"040301" = "Building Science and Technology"
		"040303" = "Building Construction Management"
		"040305" = "Building Surveying (Inspection)"
		"040307" = "Building Construction Economics (including Quantity Surveying)"
		"040309" = "Bricklaying and Stonemasonry"
		"040311" = "Carpentry and Joinery"
		"040313" = "Ceiling, Wall and Floor Fixing"
		"040315" = "Roof Fixing"
		"040317" = "Plastering"
		"040319" = "Furnishing Installation"
		"040321" = "Floor Coverings"
		"040323" = "Glazing"
		"040325" = "Painting, Decorating, Sign Writing and Other Finishes"
		"040327" = "Plumbing, Gasfitting and Drainlaying"
		"040329" = "Scaffolding and Rigging"
		"040399" = "Building nec"
		"050100" = "Agriculture nfd"
		"050101" = "Agricultural Science"
		"050103" = "Wool and Fibre Science"
		"050104" = "Beekeeping"
		"050105" = "Animal Husbandry"
		"050106" = "Crop Production"
		"050108" = "Equine Trades"
		"050110" = "Wool and Fibre Harvesting"
		"050112" = "General Land Skills"
		"050199" = "Agriculture nec"
		"050300" = "Horticulture and Viticulture nfd"
		"050301" = "Horticulture"
		"050303" = "Viticulture"
		"050500" = "Forestry Studies nfd"
		"050501" = "Forestry Studies"
		"050502" = "Solid Wood Processing"
		"050700" = "Fisheries Studies nfd"
		"050701" = "Aquaculture"
		"050702" = "Seafood Harvesting (Fishing)"
		"050799" = "Fisheries  Studies nec"
		"050900" = "Environmental Studies nfd"
		"050901" = "Land, Parks and Wildlife Management"
		"050999" = "Environmental Studies nec"
		"059900" = "Other Agriculture, Environmental and Related Studies nfd"
		"059901" = "Pest and Weed Control"
		"059999" = "Agriculture, Environmental and Related Studies nec"
		"060100" = "Medical Studies nfd"
		"060101" = "General Medicine"
		"060103" = "Surgery"
		"060105" = "Psychiatry"
		"060107" = "Obstetrics and Gynaecology"
		"060109" = "Paediatrics"
		"060111" = "Anaesthesiology"
		"060113" = "Pathology"
		"060115" = "Radiology"
		"060117" = "Internal Medicine"
		"060119" = "General Practice Medicine"
		"060199" = "Medical Studies nec"
		"060300" = "Nursing nfd"
		"060301" = "Nursing"
		"060303" = "Midwifery"
		"060308" = "Health Care Assistant"
		"060399" = "Nursing nec"
		"060500" = "Pharmacy nfd"
		"060501" = "Pharmacy"
		"060700" = "Dental Studies nfd"
		"060701" = "Dentistry"
		"060704" = "Dental Hygiene and Therapy"
		"060705" = "Dental Technology"
		"060799" = "Dental Studies nec"
		"060900" = "Optical Science nfd"
		"060901" = "Optometry"
		"060903" = "Optical Technology"
		"060999" = "Optical Science nec"
		"061100" = "Veterinary Studies nfd"
		"061101" = "Veterinary Science"
		"061103" = "Veterinary Assisting"
		"061199" = "Veterinary Studies nec"
		"061300" = "Public Health nfd"
		"061301" = "Occupational Health and Safety"
		"061303" = "Environmental Health"
		"061304" = "Hauora (Maori Health)"
		"061307" = "Health Education,  Promotion, Counselling"
		"061309" = "Community Health"
		"061311" = "Epidemiology"
		"061399" = "Public Health nec"
		"061500" = "Radiography nfd"
		"061501" = "Medical Imaging Technology (Radiography) and Radiation Therapy"
		"061700" = "Rehabilitation Therapies nfd"
		"061701" = "Physiotherapy"
		"061703" = "Occupational Therapy"
		"061705" = "Chiropractic and Osteopathy"
		"061707" = "Speech Pathology"
		"061709" = "Audiology"
		"061711" = "Massage Therapy"
		"061713" = "Podiatry"
		"061799" = "Rehabilitation Therapies nec"
		"061900" = "Complementary Therapies nfd"
		"061901" = "Naturopathy and Homeopathy"
		"061903" = "Acupuncture"
		"061905" = "Traditional Chinese Medicine"
		"061999" = "Complementary Therapies nec"
		"069900" = "Other Health nfd"
		"069901" = "Nutrition and Dietetics"
		"069903" = "Human Movement and Sports Science"
		"069905" = "Paramedical Studies"
		"069907" = "First Aid"
		"069999" = "Health nec"
		"070100" = "Teacher Education nfd"
		"070101" = "Teacher Education: Early Childhood (Pre-Service)"
		"070103" = "Teacher Education: Primary (Pre-Service)"
		"070105" = "Teacher Education: Secondary (Pre-Service)"
		"070106" = "Teacher Education:  Tertiary"
		"070108" = "Teacher Education: General (Pre-Service)"
		"070113" = "Teacher Education: Special Education"
		"070115" = "English Language Teaching(ESOL/EFL)"
		"070116" = "Te Matauranga Maori me te Whakangungu (Maori Education)"
		"070118" = "Bilingual Early Childhood Teacher Training (Pre-Service)"
		"070120" = "Immersion Early Childhood Teacher Training (Pre-Service)"
		"070122" = "Bilingual Primary Teacher Training (Pre-Service)"
		"070124" = "Immersion Primary Teacher Training (Pre-Service)"
		"070126" = "Bilingual Secondary Teacher Training (Pre-Service)"
		"070128" = "Immersion Secondary Teacher Training (Pre-Service)"
		"070130" = "Teacher Professional Development"
		"070199" = "Teacher Education nec"
		"070300" = "Curriculum and Education Studies nfd"
		"070301" = "Curriculum Studies"
		"070303" = "Education Studies"
		"079900" = "Other Education nfd"
		"079999" = "Education nec"
		"080100" = "Accountancy nfd"
		"080101" = "Accounting"
		"080199" = "Accountancy nec"
		"080300" = "Business and Management nfd"
		"080301" = "Business Management"
		"080303" = "Human Resource Management"
		"080305" = "Personal Management Training"
		"080307" = "Organisation Management"
		"080309" = "Industrial Relations"
		"080311" = "International Business"
		"080312" = "Education Administration"
		"080313" = "Public and Health Care Administration"
		"080315" = "Project Management"
		"080317" = "Quality Management"
		"080319" = "Hospitality Management"
		"080320" = "Racing and Gaming Management"
		"080321" = "Farm Management and Agribusiness"
		"080323" = "Tourism Management"
		"080399" = "Business and Management nec"
		"080500" = "Sales and Marketing nfd"
		"080501" = "Sales"
		"080503" = "Real Estate"
		"080505" = "Marketing"
		"080507" = "Advertising"
		"080509" = "Public Relations"
		"080599" = "Sales and Marketing nec"
		"080700" = "Tourism nfd"
		"080701" = "Tourism Studies"
		"080900" = "Office Studies nfd"
		"080901" = "Secretarial and Office Studies"
		"080904" = "Text Processing and Office Tools"
		"080999" = "Office Studies nec"
		"081100" = "Banking, Finance and Related Fields nfd"
		"081101" = "Banking and Finance"
		"081103" = "Insurance and Actuarial Studies"
		"081105" = "Investment and Securities"
		"081199" = "Banking, Finance and Related Fields nec"
		"089900" = "Other Management and Commerce nfd"
		"089901" = "Purchasing, Warehousing and Distribution"
		"089903" = "Valuation"
		"089999" = "Management and Commerce nec"
		"090100" = "Political Science and Policy Studies nfd"
		"090101" = "Political Science"
		"090103" = "Policy Studies"
		"090300" = "Studies in Human Society nfd"
		"090301" = "Sociology"
		"090303" = "Anthropology"
		"090305" = "History"
		"090306" = "Art History"
		"090307" = "Archaeology"
		"090308" = "Classics"
		"090309" = "Human Geography"
		"090314" = "Tikanga - Maori Customs"
		"090316" = "Women's Studies"
		"090399" = "Studies in Human Society nec"
		"090500" = "Human Welfare Studies and Services nfd"
		"090501" = "Social Work"
		"090502" = "Children's Services"
		"090503" = "Nannying and Early Childhood Care"
		"090505" = "Youth Work"
		"090507" = "Support for the Older Person"
		"090509" = "Care for People with Disabilities"
		"090511" = "Community Client Care"
		"090513" = "Counselling"
		"090515" = "Welfare Studies"
		"090599" = "Human Welfare Studies and Services nec"
		"090700" = "Behavioural Science nfd"
		"090701" = "Psychology"
		"090799" = "Behavioural Science nec"
		"090900" = "Law nfd"
		"090901" = "Business and Commercial Law"
		"090903" = "Constitutional Law"
		"090905" = "Criminal Law"
		"090907" = "Family Law"
		"090909" = "International Law"
		"090911" = "Taxation Law"
		"090913" = "Legal Practice"
		"090999" = "Law nec"
		"091100" = "Justice and Law Enforcement nfd"
		"091101" = "Justice Administration"
		"091103" = "Legal Studies"
		"091105" = "Police Studies"
		"091199" = "Justice and Law Enforcement nec"
		"091300" = "Librarianship, Information Management and Curatorial Studies nfd"
		"091301" = "Librarianship and Information Management"
		"091303" = "Curatorial Studies"
		"091500" = "Language and Literature nfd"
		"091501" = "English Language"
		"091502" = "Te Reo Maori"
		"091504" = "Foreign Languages"
		"091506" = "English for Speakers of Other Languages"
		"091519" = "Translating and Interpreting"
		"091521" = "Linguistics"
		"091523" = "Literature"
		"091599" = "Language and Literature nec"
		"091700" = "Philosophy and Religious Studies nfd"
		"091701" = "Philosophy"
		"091703" = "Religious Studies"
		"091900" = "Economics and Econometrics nfd"
		"091901" = "Economics"
		"091903" = "Econometrics"
		"092100" = "Sport and Recreation nfd"
		"092101" = "Sport and Recreation Activities"
		"092103" = "Sports Coaching, Playing, Officiating and Instructing"
		"092199" = "Sport and Recreation nec"
		"099900" = "Other Society and Culture nfd"
		"099901" = "Community, Whanau, Family and Consumer Studies"
		"099902" = "Cultural Studies"
		"099903" = "Criminology"
		"099905" = "Security Services"
		"099999" = "Society and Culture nec"
		"100100" = "Performing Arts nfd"
		"100101" = "Music"
		"100103" = "Drama and Theatre Studies"
		"100105" = "Dance"
		"100106" = "Nga Mahi a Rehia (Maori Performing Arts)"
		"100199" = "Performing Arts nec"
		"100300" = "Visual Arts and Crafts nfd"
		"100301" = "Fine Arts"
		"100303" = "Photography"
		"100305" = "Crafts"
		"100306" = "Mana Whakairo (Maori Carving)"
		"100307" = "Jewellery Making"
		"100309" = "Floristry"
		"100399" = "Visual Arts and Crafts nec"
		"100500" = "Graphic and Design Studies nfd"
		"100501" = "Graphic Arts and Design Studies"
		"100503" = "Textile Design"
		"100505" = "Fashion Design"
		"100506" = "Nga Mahi a te Whare Pora (Maori Weaving)"
		"100599" = "Graphic and Design Studies nec"
		"100700" = "Communication and Media Studies nfd"
		"100701" = "Audio Visual Studies"
		"100703" = "Journalism, Communication and Media Studies"
		"100705" = "Written Communication"
		"100707" = "Verbal Communication"
		"100799" = "Communication and Media Studies nec"
		"109900" = "Other Creative Arts nfd"
		"109999" = "Creative Arts nec"
		"110100" = "Food and Hospitality nfd"
		"110101" = "Hospitality"
		"110103" = "Food and Beverage Service"
		"110105" = "Butchery"
		"110107" = "Baking and Pastry Making"
		"110109" = "Cookery"
		"110111" = "Food Hygiene"
		"110199" = "Food and Hospitality nec"
		"110300" = "Personal Services nfd"
		"110301" = "Beauty Therapy"
		"110303" = "Hairdressing"
		"110399" = "Personal Services nec"
		"120100" = "General Education Programmes nfd"
		"120101" = "General Primary and Secondary Education"
		"120103" = "Literacy and Numeracy Programmes"
		"120105" = "Learning Skills Programmes"
		"120199" = "General Education Programmes nec"
		"120300" = "Social Skills Programmes nfd"
		"120301" = "Social and Interpersonal Skills Programmes"
		"120303" = "Life Skills"
		"120304" = "Family/Whanau Education"
		"120399" = "Social Skills Programmes nec"
		"120500" = "Employment Skills Programmes nfd"
		"120501" = "Career Development Programmes"
		"120503" = "Job Search Skills Programmes"
		"120505" = "Work Practices Programmes"
		"120599" = "Employment Skills Programmes nec"
		"129900" = "Other Mixed Field Programmes nfd"
		"129999" = "Mixed Field Programmes nec"
		Other	 = "ERROR";

	*** standard labels for nzsced at narrow level - last updated 24/7/2006;
	value $nzscedn
		"0101" = "Mathematical Sciences"
		"0103" = "Physics and Astronomy"
		"0105" = "Chemical Sciences"
		"0107" = "Earth Sciences"
		"0109" = "Biological Sciences"
		"0199" = "Other Natural and Physical Sciences"
		"0201" = "Computer Science"
		"0203" = "Information Systems"
		"0299" = "Other Information Technology"
		"0301" = "Manufacturing, Engineering and Technology"
		"0303" = "Process and Resources Engineering"
		"0305" = "Automotive Engineering and Technology"
		"0307" = "Mechanical and Industrial Engineering and Technology"
		"0309" = "Civil Engineering"
		"0311" = "Geomatic Engineering"
		"0313" = "Electrical and Electronic Engineering and Technology"
		"0315" = "Aerospace Engineering and Technology"
		"0317" = "Maritime Engineering and Technology"
		"0399" = "Other Engineering and Related Technologies"
		"0401" = "Architecture and Urban Environment"
		"0403" = "Building"
		"0501" = "Agriculture"
		"0503" = "Horticulture and Viticulture"
		"0505" = "Forestry Studies"
		"0507" = "Fisheries Studies"
		"0509" = "Environmental Studies"
		"0599" = "Other Agriculture, Environmental and Related Studies"
		"0601" = "Medical Studies"
		"0603" = "Nursing"
		"0605" = "Pharmacy"
		"0607" = "Dental Studies"
		"0609" = "Optical Science"
		"0611" = "Veterinary Studies"
		"0613" = "Public Health"
		"0615" = "Radiography"
		"0617" = "Rehabilitation Therapies"
		"0619" = "Complementary Therapies"
		"0699" = "Other Health"
		"0701" = "Teacher Education"
		"0703" = "Curriculum and Education Studies"
		"0799" = "Other Education"
		"0801" = "Accountancy"
		"0803" = "Business and Management"
		"0805" = "Sales and Marketing"
		"0807" = "Tourism"
		"0809" = "Office Studies"
		"0811" = "Banking, Finance and Related Fields"
		"0899" = "Other Management and Commerce"
		"0901" = "Political Science and Policy Studies"
		"0903" = "Studies in Human Society"
		"0905" = "Human Welfare Studies and Services"
		"0907" = "Behavioural Science"
		"0909" = "Law"
		"0911" = "Justice and Law Enforcement"
		"0913" = "Librarianship, Information Management and Curatorial Studies"
		"0915" = "Language and Literature"
		"0917" = "Philosophy and Religious Studies"
		"0919" = "Economics and Econometrics"
		"0921" = "Sport and Recreation "
		"0999" = "Other Society and Culture"
		"1001" = "Performing Arts"
		"1003" = "Visual Arts and Crafts"
		"1005" = "Graphic and Design Studies"
		"1007" = "Communication and Media Studies"
		"1099" = "Other Creative Arts"
		"1101" = "Food and Hospitality"
		"1103" = "Personal Services"
		"1201" = "General Education Programmes"
		"1203" = "Social Skills Programmes"
		"1205" = "Employment Skills Programmes"
		"1299" = "Other Mixed Field Programmes"
		"T"	   = "Total"
		Other  = "ERROR";

	*** standard labels for nzsced at broad level - last updated 24/7/2006;
	value $nzscedb
		"01"	=	"Natural and physical sciences"
		"02"	=	"Information technology"
		"03"	=	"Engineering and related technologies"
		"04"	=	"Architecture and building"
		"05"	=	"Agriculture, environmental and related studies"
		"06"	=	"Health"
		"07"	=	"Education"
		"08"	=	"Management and commerce"
		"09"	=	"Society and culture"
		"10"	=	"Creative arts"
		"11"	=	"Food, hospitality and personal services"
		"12"	=	"Mixed field programmes"
	    "T" 	=   "Total students" 
		"Other"	=	"ERROR";

	*** standard labels for nzsced at narrow level - last updated 24/7/2006, "T" = "Total students" removed 30 Jan 2017 as causes error as two values for "T"... ;
	value $nzscednb
		"01"	=	"Natural and physical sciences"
		"02"	=	"Information technology"
		"03"	=	"Engineering and related technologies"
		"04"	=	"Architecture and building"
		"05"	=	"Agriculture, environmental and related studies"
		"06"	=	"Health"
		"07"	=	"Education"
		"08"	=	"Management and commerce"
		"09"	=	"Society and culture"
		"10"	=	"Creative arts"
		"11"	=	"Food, hospitality and personal services"
		"12"	=	"Mixed field programmes"
	    
		"0101" = "Mathematical Sciences"
		"0103" = "Physics and Astronomy"
		"0105" = "Chemical Sciences"
		"0107" = "Earth Sciences"
		"0109" = "Biological Sciences"
		"0199" = "Other Natural and Physical Sciences"
		"0201" = "Computer Science"
		"0203" = "Information Systems"
		"0299" = "Other Information Technology"
		"0301" = "Manufacturing, Engineering and Technology"
		"0303" = "Process and Resources Engineering"
		"0305" = "Automotive Engineering and Technology"
		"0307" = "Mechanical and Industrial Engineering and Technology"
		"0309" = "Civil Engineering"
		"0311" = "Geomatic Engineering"
		"0313" = "Electrical and Electronic Engineering and Technology"
		"0315" = "Aerospace Engineering and Technology"
		"0317" = "Maritime Engineering and Technology"
		"0399" = "Other Engineering and Related Technologies"
		"0401" = "Architecture and Urban Environment"
		"0403" = "Building"
		"0501" = "Agriculture"
		"0503" = "Horticulture and Viticulture"
		"0505" = "Forestry Studies"
		"0507" = "Fisheries Studies"
		"0509" = "Environmental Studies"
		"0599" = "Other Agriculture, Environmental and Related Studies"
		"0601" = "Medical Studies"
		"0603" = "Nursing"
		"0605" = "Pharmacy"
		"0607" = "Dental Studies"
		"0609" = "Optical Science"
		"0611" = "Veterinary Studies"
		"0613" = "Public Health"
		"0615" = "Radiography"
		"0617" = "Rehabilitation Therapies"
		"0619" = "Complementary Therapies"
		"0699" = "Other Health"
		"0701" = "Teacher Education"
		"0703" = "Curriculum and Education Studies"
		"0799" = "Other Education"
		"0801" = "Accountancy"
		"0803" = "Business and Management"
		"0805" = "Sales and Marketing"
		"0807" = "Tourism"
		"0809" = "Office Studies"
		"0811" = "Banking, Finance and Related Fields"
		"0899" = "Other Management and Commerce"
		"0901" = "Political Science and Policy Studies"
		"0903" = "Studies in Human Society"
		"0905" = "Human Welfare Studies and Services"
		"0907" = "Behavioural Science"
		"0909" = "Law"
		"0911" = "Justice and Law Enforcement"
		"0913" = "Librarianship, Information Management and Curatorial Studies"
		"0915" = "Language and Literature"
		"0917" = "Philosophy and Religious Studies"
		"0919" = "Economics and Econometrics"
		"0921" = "Sport and Recreation "
		"0999" = "Other Society and Culture"
		"1001" = "Performing Arts"
		"1003" = "Visual Arts and Crafts"
		"1005" = "Graphic and Design Studies"
		"1007" = "Communication and Media Studies"
		"1099" = "Other Creative Arts"
		"1101" = "Food and Hospitality"
		"1103" = "Personal Services"
		"1201" = "General Education Programmes"
		"1203" = "Social Skills Programmes"
		"1205" = "Employment Skills Programmes"
		"1299" = "Other Mixed Field Programmes"
		"T"	   = "Total"
		Other  = "ERROR";



*** PBRF eligible;
	*** standard labels;
	value $pbrf_eligible
		"M"	=	"Masters (>0.75 efts)"
		"D"	=	"Doctorate (>0.75 efts) "
		"L"	=	"Part-time Masters"
		"C"	=	"Part-time Doctorate"
		"X"	=	"Not PBRF Eligible"
		""	=	"Unknown"
		Other	=	"ERROR";

*** PRIOR_A: MAIN ACTIVITY AT 1 OCTOBER IN YEAR PRIOR TO FORMAL ENROLMENT AT THIS INSTITUTION;
	*** standard labels;
	value $prior_a
		"01"	=	"Secondary school student"
		"02"	=	"Non-employed or beneficiary"
		"03"	=	"Wage or salary worker"
		"04"	=	"Self-employed"
		"05"	=	"University student"
		"06"	=	"Polytechnic student"
		"07"	=	"College of Education student"
		"08"	=	"House person or retired"
		"09"	=	"Overseas"
		"11"	=	"Private Training Establishment student"
		"12"	=	"Wananga student"
		""		=	"Unknown"
		Other	=	"ERROR";

	*** standard grouping :sort order ids;
	value $paid
		"01"	                           	="1"
		"05","06","07","11","12"			="2"
		"03","04"			                ="3"
		"02"			                    ="4"
		"08"								="5"
		"09"                	            ="6"
		Other                               ="9";

	*** standard grouping :labels;
	value $pa
		"1"     ="School"
		"2"	    ="Tertiary"
		"3"     ="Employed or self-employed"
		"4"     ="Non-employed or beneficiary"
		"5"     ="House-person or retired"
		"6"     ="Overseas"
		"9"     ="Unknown"
		"T"		="Total";

*** QACC: QUALIFICATION AWARD CATEGORY CODE AND LEVEL OF STUDY;
	*** standard labels;
	value $qacc
		"01"=	"Higher doctorate"
		"10"=	"PhD"
		"11"=	"Masters"
		"12"=	"Bachelors with honours"
		"13"=	"Post-graduate diplomas"
		"14"=	"Post-graduate certificates"
		"20"=	"Bachelors"
		"21"=	"Graduate diploma/ certificate"
		"25"=	"Certificate of proficiency (credit to a Degree)"
		"30"=	"Professional association diploma"
		"31"=	"National diploma/ national certificate levels 5-7"
		"32"=	"New Zealand diploma"
		"33"=	"Diploma/ certificate issued by TEO levels 5-7"
		"34"=	"Advanced trade certificate"
		"35"=	"New Zealand certificate/ technicians certificate"
		"36"=	"National certificate level 4 and other level 4 certificates"
		"37"=	"Certificate of proficiency (credit to a diploma)"
		"40"=	"Professional association certificate"
		"41"=	"National certificate levels 1-3"
		"43"=	"Trade certificate level 4"
		"46"=	"Certificate issued by TEO levels 1-3"
		"60"=	"Licence"
		"90"=	"Certificate of personal interest"
		"96"=	"STAR"
		"97"=	"Programmes of study taught under contract"
		"98"=	"Programmes of study made up of selected unit standards"
		"99"=	"Community education programmes"
		"T" =   "Total"
		Other = "ERROR";

****** Qual_Type *****;
	value $qual_type 
		"B" = "Formal short course"
		"C" = "Non-formal"
		"D" = "Formal"
		"S" = "STAR"	
		Other = "ERROR";


*** REGISTER LEVEL;
	*** standard labels;
	value $register_level
		"01"	=	"Level 1"
		"02"	=	"Level 2"
		"03"	=	"Level 3"
		"04"	=	"Level 4"
		"05"	=	"Level 5"
		"06"	=	"Level 6"
		"07"	=	"Level 7"
		"08"	=	"Level 8"
		"09"	=	"Level 9"
		"10"	=	"Level 10"
		""		=	"Unknown"
		Other 	= 	"ERROR";

*** S_SCHOOL: LAST SECONDARY SCHOOL ATTENDED;
*** standard labels;
*** As new schools were introduced new format $S_SCHOOL. has been created from reference table - Sathi 11 March 2008 ******;
*** Refer "I:/Data/TSEC/Formats/Formats_Ref_Tables.sas" for more details. *******;

*** SEC_QUAL: HIGHEST SECONDARY SCHOOL QUALIFICATION ;
	*** standard labels;

	****** Secondary qualifications - introduced from 2007 - conversion of old codes to new
			is work in progress so for time being store both - DS 15-8-08 ******;
	value $sec_qual_all
		"00" = "No formal secondary school qualification/ 0-13 NCEA Level 1 credits"
		"01" = "School Certificate/ 14+ NCEA Level 1 credits/ NCEA Level 1"
		"02" = "Sixth Form Certificate/ 30+ NCEA Level 2 credits"
		"03" = "University Entrance/ NCEA Level 2"
		"04" = "Higher School Certificate/ 30+ NCEA Level 3 credits"
		"05" = "Entrance Qual from Bursary/ 42+ NCEA Level 3 credits"
		"07" = "A or B Bursary / NCEA Level 3"
		"08" = "Scholarship/ NCEA Level 4"
		"09" = "Overseas qualification (includes International Baccalaureate)"
		"11" = "14 or more credits at any level"		
		"12" = "NCEA level 1 or school certificate " 		
		"13" = "NCEA level 2 or 6th form certificate" 		
		"14" = "University Entrance" 					
		"15" = "NCEA level 3 or Bursary or scholarship" 
		"98" = "Other"
		"" 	 = "Unknown"
		"T"  = "Total"
		Other = "ERROR";

	value $sec_qual_new
		"00" = "No formal secondary school qualification/ 0-13 NCEA Level 1 credits"
		"09" = "Overseas qualification (includes International Baccalaureate)"
		"11" = "14 or more credits at any level"			/* New Code			*/
		"12" = "NCEA level 1 or school certificate " 		/* maps old code 01 */
		"13" = "NCEA level 2 or 6th form certificate" 		/*maps old code 02 */
		"14" = "University Entrance" 						/* maps old codes 03 04 05 */
		"15" = "NCEA level 3 or Bursary or scholarship" 	/* maps old code 07 */
		"98" = "Other"
		"" 	 = "Unknown"
		"T"  = "Total"
		Other = "ERROR";

	value $sec_qual_old
		"00" = "No formal secondary school qualification/ 0-13 NCEA Level 1 credits"
		"01" = "School Certificate/ 14+ NCEA Level 1 credits/ NCEA Level 1"
		"02" = "Sixth Form Certificate/ 30+ NCEA Level 2 credits"
		"03" = "University Entrance/ NCEA Level 2"
		"04" = "Higher School Certificate/ 30+ NCEA Level 3 credits"
		"05" = "Entrance Qual from Bursary/ 42+ NCEA Level 3 credits"
		"07" = "A or B Bursary / NCEA Level 3"
		"08" = "Scholarship/ NCEA Level 4"
		"09" = "Overseas qualification (includes International Baccalaureate)"
		"98" = "Other"
		"" 	= "Unknown"
		Other = "ERROR";

******* Converting old secondary qualification codes to new ones ******;

	VALUE $sec_qual_conversion
		"00" = "00"
		"01" = "12"
		"02" = "13"
		"03", "04", "05" = "14"
		"07", "08" = "15"
		"09" = "09"
		"98" = "98"
		"99" = "";

*** STUDY_REGION: REGIONAL COUNCIL OF INSTITUTION (OF MAIN OR ADMINISTRATIVE CENTRE);
	*** standard labels;
	value $study_region
		"01" = "Northland Region"
		"02" = "Auckland Region"
		"03" = "Waikato Region"
		"04" = "Bay of Plenty Region"
		"05" = "Gisborne Region"
		"06" = "Hawkes Bay Region"
		"07" = "Taranaki Region"
		"08" = "Manawatu-Wanganui Region"
		"09" = "Wellington Region"
		"10" = "Nelson-Marlborough Region"
		"12" = "West Coast Region"
		"13" = "Canterbury Region"
		"14" = "Otago Region"
		"15" = "Southland Region"
		"16" = "Tasman Region"
		"17" = "Nelson Region"
		"18" = "Marlborough Region"
		"19" = "Chatham Islands County"
		"98" = "Extramural"
		"" 	 = "Unknown"
		Other	= "ERROR";

*** STUDY_TA: TERRITORIAL AUTHORITY OF INSTITUTION (OF MAIN OR ADMINISTRATIVE CENTRE);
	*** standard labels;
	value $study_ta
		"01" = "Far North District"
		"02" = "Whangarei District"
		"03" = "Kaipara District"
		"04" = "Rodney District"
		"05" = "North Shore City"
		"06" = "Waitakere City"
		"07" = "Auckland City"
		"08" = "Manukau City"
		"09" = "Papakura District"
		"10" = "Franklin District"
		"11" = "Thames-Coromandel District"
		"12" = "Hauraki District"
		"13" = "Waikato District"
		"15" = "Matamata-Piako District"
		"16" = "Hamilton City"
		"17" = "Waipa District"
		"18" = "Otorohanga District"
		"19" = "South Waikato District"
		"20" = "Waitomo District"
		"21" = "Taupo District"
		"22" = "Western Bay of Plenty District"
		"23" = "Tauranga District"
		"24" = "Rotorua District"
		"25" = "Whakatane District"
		"26" = "Kawerau District"
		"27" = "Opotiki District"
		"28" = "Gisborne District"
		"29" = "Wairoa District"
		"30" = "Hastings District"
		"31" = "Napier City"
		"32" = "Central Hawkes Bay District"
		"33" = "New Plymouth District"
		"34" = "Stratford District"
		"35" = "South Taranaki District"
		"36" = "Ruapehu District"
		"37" = "Wanganui District"
		"38" = "Rangitikei District"
		"39" = "Manawatu District"
		"40" = "Palmerston North City"
		"41" = "Tararua District"
		"42" = "Horowhenua District"
		"43" = "Kapiti Coast District"
		"44" = "Porirua City"
		"45" = "Upper Hutt City"
		"46" = "Lower Hutt City"
		"47" = "Wellington City"
		"48" = "Masterton District"
		"49" = "Carterton District"
		"50" = "South Wairarapa District"
		"51" = "Tasman District"
		"52" = "Nelson City"
		"53" = "Marlborough District"
		"54" = "Kaikoura District"
		"55" = "Buller District"
		"56" = "Grey District"
		"57" = "Westland District"
		"58" = "Hurunui District"
		"59" = "Waimakariri District"
		"60" = "Christchurch City"
		"61" = "Banks Peninsula District"
		"62" = "Selwyn District"
		"63" = "Ashburton District"
		"64" = "Timaru District"
		"65" = "McKenzie District"
		"66" = "Waimate District"
		"67" = "Chatham Islands County"
		"68" = "Waitaki District"
		"69" = "Central Otago District"
		"70" = "Queenstown-Lakes District"
		"71" = "Dunedin City"
		"72" = "Clutha District"
		"73" = "Southland District"
		"74" = "Gore District"
		"75" = "Invercargill City"
		"76" = "Devenport Borough"
		"98" = "Extramural"
		"" 	 = "Unknown"
		Other = "ERROR";


*** STUDY_TYPE: TYPE OF STUDY;
	*** standard labels;
	value $study_type
		"1" = "Full-time full-year"
		"2" = "Full-time part-year"
		"3" = "Part-time full-year"
		"4" = "Part-time part-year"
		"T" = "Total"
		Other= "ERROR";



*** SUBFIELD: FIELD OF STUDY AND SUBFIELD OF STUDY ---- No longer used;
	*** standard labels;
	value $subfield
		"0100" = "General Spectrum Programmes"
		"0170" = "Doctorate programmes"
		"0821" = "Functional Literacy Programmes"
		"1402" = "Advanced Studies for Teachers"
		"1408" = "Tutor Training/ Teaching Adults"
		"1411" = "Early Childhood Bilingual"
		"1412" = "Early Childhood Education"
		"1413" = "Early Childhood Equivalency"
		"1414" = "Early Childhood Education: Other"
		"1422" = "Special Education Teacher Training"
		"1423" = "Special Education: Other Training"
		"1432" = "Primary Teacher Training"
		"1433" = "Primary Bilingual Teacher Training"
		"1434" = "Primary Immersion Teacher Training"
		"1435" = "Primary Bilingual (post-service)"
		"1440" = "Pre-service Teacher Training (All Types)"
		"1442" = "Secondary Teacher Training"
		"1443" = "Secondary Teacher Training (post-service)"
		"1450" = "Specific Education Programmes"
		"1451" = "Education Psychology"
		"1452" = "Education Management"
		"1470" = "General Education Programmes"
		"1499" = "Education nec"
		"1801" = "General Art Studies Programmes"
		"1802" = "History & Philosophy of Art"
		"1804" = "Drawing & Painting"
		"1808" = "Sculpture"
		"1810" = "Visual & Graphic Design"
		"1811" = "Maori Design/Crafts"
		"1812" = "Handcrafts & Crafts Design"
		"1813" = "Floral Art"
		"1814" = "Pottery & Ceramics"
		"1815" = "Leather Crafts"
		"1816" = "Jewellery"
		"1822" = "Music & Singing"
		"1832" = "Performing Arts"
		"1842" = "Photography, Video, Camera"
		"1852" = "Interior Design"
		"1853" = "Antiques"
		"1854" = "Furniture Restoration/ Woodturning & Carving"
		"1870" = "General Crafts Programmes"
		"1899" = "Art, Music, Handicrafts nec"
		"2211" = "Maori Language"
		"2213" = "English Language/Literature"
		"2215" = "Foreign Languages: 'Living'"
		"2221" = "Foreign Languages: 'Dead'"
		"2241" = "Literature"
		"2251" = "History"
		"2252" = "Geography"
		"2261" = "Archaeology"
		"2270" = "General Arts Programmes"
		"2271" = "Philosophy"
		"2299" = "Humanities nec"
		"2610" = "Religious Studies"
		"2620" = "Theology"
		"2699" = "Religion & Theology nec"
		"3010" = "Maori Studies/ Culture"
		"3012" = "Social Work"
		"3022" = "Political Science"
		"3032" = "Sociology"
		"3040" = "Research Methods"
		"3052" = "Psychology"
		"3053" = "Communication Skills"
		"3054" = "Community Social Services"
		"3055" = "Caring Programmes"
		"3056" = "Counselling"
		"3060" = "Life Skills"
		"3063" = "Human Resource Management"
		"3064" = "Industrial Relations"
		"3070" = "General Social Science Programmes"
		"3080" = "I.H.C. Programmes"
		"3099" = "Social, Behavioural, Communication Skills nec"
		"3401" = "General Commercial & Admin Program"
		"3402" = "Typing/ Word-processing/ Keyboard"
		"3404" = "Shorthand, Typing, Word-processing"
		"3408" = "Clerical or Office Systems"
		"3426" = "Business Computing/Info. Systems"
		"3428" = "Secretarial Programmes"
		"3430" = "Receptionist"
		"3432" = "Accountancy/Economics"
		"3434" = "Business Admin/ Mgmt/ Marketing"
		"3435" = "Regional/Local Government Administration"
		"3436" = "Financial Management"
		"3437" = "Educational Management"
		"3438" = "Property Management"
		"3439" = "Valuation"
		"3440" = "Agricultural Business/Management"
		"3470" = "General Business & Administration"
		"3499" = "Commercial & Business nec"
		"3801" = "General Law"
		"3810" = "Commercial Law"
		"3812" = "Family Law"
		"3815" = "Other Specialist Areas"
		"3820" = "Legal Studies"
		"3823" = "Legal Executive"
		"3870" = "General Law Programmes"
		"3899" = "Law nec"
		"4201" = "General Science"
		"4202" = "Biology/Biological Science"
		"4212" = "Chemistry"
		"4222" = "Geology/Geological Science"
		"4232" = "Physics"
		"4242" = "Astronomy"
		"4253" = "Meteorology"
		"4262" = "Marine Science/ Oceanography"
		"4263" = "Environmental Science"
		"4264" = "Applied Science/ Technology"
		"4266" = "Health Education/ Science"
		"4267" = "Animal Science"
		"4270" = "General Science Programmes"
		"4299" = "Natural & Applied Sciences nec"
		"4601" = "General Mathematics"
		"4611" = "Statistics"
		"4612" = "Financial Mathematics"
		"4620" = "Remedial Mathematics"
		"4630" = "Operations Research"
		"4640" = "Mathematics & Computer Studies"
		"4699" = "Mathematics nec"
		"4801" = "Introductory Computer Programmes"
		"4820" = "Computer Awareness Programmes"
		"4822" = "Computer Software"
		"4824" = "Computer Operation"
		"4826" = "Computer Programming/ Analysis"
		"4830" = "Information Management"
		"4840" = "Computer Science"
		"4870" = "General Computer Programmes"
		"4899" = "Computing nec"
		"5001" = "Introductory Health Programmes"
		"5002" = "Public & Environmental Health"
		"5004" = "Medicine & Surgery (pre-service)"
		"5005" = "Medicine & Surgery (post-service)"
		"5006" = "Medicine & Surgery"
		"5007" = "Natural Healing/Health"
		"5008" = "Occupational Therapy"
		"5012" = "Nursing"
		"5013" = "Other Nursing Programmes"
		"5015" = "Midwifery"
		"5017" = "Radiography"
		"5018" = "Para-medical"
		"5019" = "Sports Medicine"
		"5020" = "Health Care Assistants"
		"5024" = "Podiatry"
		"5030" = "Medical Technology"
		"5040" = "Physiotherapy"
		"5042" = "Dentistry"
		"5043" = "Dental Therapy/Assistant"
		"5052" = "Pharmacy/Pharmacology"
		"5053" = "Pharmacy Assistant"
		"5060" = "Audiology"
		"5062" = "Optometry"
		"5070" = "General Health Programmes"
		"5099" = "Medical & Health nec"
		"5201" = "General Trade Programmes"
		"5212" = "Food Processing"
		"5216" = "Building Trades"
		"5218" = "Painting & Decorating"
		"5220" = "Plumbing, Gasfitting, Drainlaying"
		"5222" = "Electrical & Electronic Trades"
		"5232" = "Metal Trades"
		"5233" = "Plastics/Glass Trades"
		"5242" = "Mechanical & Repair Trades"
		"5243" = "Panel Repair/Coach Building"
		"5250" = "Instrumentation"
		"5262" = "Woodworking Trades"
		"5264" = "Heating/ Air-conditioning/ Refrigeration."
		"5265" = "Marine/Boat Building"
		"5266" = "Industrial Design"
		"5267" = "Production Process"
		"5272" = "Leather Trades"
		"5274" = "Clothing & Textiles"
		"5276" = "Clothing & Textiles"
		"5278" = "Graphic Arts & Printing"
		"5279" = "Watchmaking/ Jewellery"
		"5284" = "Laboratory"
		"5290" = "Quality Assurance"
		"5299" = "Industrial Trades & Crafts nec"
		"5401" = "Engineering Technician/Assistant"
		"5402" = "Surveying"
		"5406" = "Draughting & Design"
		"5408" = "Quantity Surveying"
		"5412" = "Chemical Engineering"
		"5416" = "Civil Engineering"
		"5422" = "Electrical/ Electronics Engineering"
		"5423" = "Electrical/ Electronics Engineering"
		"5426" = "Industrial Engineering"
		"5436" = "Mineral/ Mining Engineering"
		"5442" = "Mechanical Engineering"
		"5444" = "Aeronautical Engineering"
		"5450" = "Technology"
		"5452" = "Agricultural/ Forestry/ Fishery Engineering"
		"5464" = "Heating, Ventilating"
		"5470" = "General Engineering Programmes"
		"5499" = "Engineering nec"
		"5802" = "Architecture"
		"5804" = "Building Science"
		"5812" = "Landscape Architecture"
		"5822" = "Town Planning"
		"5830" = "Resource Planning/ Management"
		"5899" = "Architecture, Town Planning, Resource Mgmt nec"
		"6201" = "General Agriculture/ Farming"
		"6203" = "Animal Husbandry"
		"6206" = "Horticulture"
		"6208" = "Crop Husbandry"
		"6212" = "Agricultural Economics"
		"6214" = "Farm Product Technology"
		"6226" = "Soil/ Water Science"
		"6232" = "Animal Health"
		"6262" = "Forestry/Forest Products"
		"6270" = "General Agriculture/ Forestry/ Fishery Programmes"
		"6272" = "Fishery"
		"6280" = "Conservation"
		"6299" = "Agriculture, Forestry, Fishery nec"
		"7002" = "Aircrew Programmes"
		"7004" = "Programmes for Sailors"
		"7006" = "Railway Operations"
		"7008" = "Road Vehicle Operations"
		"7010" = "Telecommunications"
		"7099" = "Transport & Communications nec"
		"7812" = "Hairdressing & Beauty Trades"
		"7814" = "Floristry"
		"7816" = "Retailing"
		"7822" = "Hotel & Restaurant Trades/ Cooking"
		"7862" = "Retailing Trades/ Sales Skills"
		"7872" = "Tourism (travel)"
		"7874" = "Tourism & Hospitality Trades"
		"7875" = "Embalming, Funeral Director"
		"7876" = "Celebrant (marriage, funeral)"
		"7899" = "Service Trades nec"
		"8402" = "Journalism/ Media Studies"
		"8404" = "Radio & Television/ Film Making"
		"8407" = "Public Relations"
		"8422" = "Librarianship"
		"8423" = "Advertising"
		"8499" = "Mass Communications nec"
		"8912" = "Police & Law Enforcement"
		"8915" = "Fire Fighting & Fire Protection"
		"8917" = "Military Training"
		"8919" = "Civil Security"
		"9002" = "Team Sports"
		"9004" = "Individual Sports"
		"9006" = "Sedentary Games"
		"9008" = "Keep Fit, Health, Leisure"
		"9010" = "Sport & Recreation"
		"9012" = "Sports Science/ Coaching"
		"9070" = "General Physical Education Program"
		"9099" = "Sport & Recreation nec"
		"9204" = "Foundation/ Introduction to Tertiary Study"
		"9802" = "Training Opportunities Programmes"
		"9804" = "Link, STAR, Short Courses for Schools"
		"9899" = "Other Programmes nec"
		"" 	= "Unknown"
		Other  = "ERROR";

	*** standard labels for field (first 2 characters);
	value $field
		"01" = "General Programmes"
		"08" = "Literacy"
		"14" = "Education"
		"18" = "Art, Music, Handicrafts"
		"22" = "Humanities"
		"26" = "Religion & Theology"
		"30" = "Social, Behavioural, Communication Skills"
		"34" = "Commercial & Business"
		"38" = "Law"
		"42" = "Natural & Applied Sciences"
		"46" = "Mathematics"
		"48" = "Computing"
		"50" = "Medical & Health"
		"52" = "Industrial Trades & Crafts"
		"54" = "Engineering"
		"58" = "Architecture, Town Planning, Resource Mgmt"
		"62" = "Agriculture, Forestry, Fishing"
		"70" = "Transport & Communications"
		"78" = "Service Trades"
		"84" = "Mass Communications"
		"89" = "Other Para-Professional Occupations"
		"90" = "Sport and Recreation"
		"92" = "General Foundation Courses"
		"98" = "Other Formal Programmes"
		"  " = "Unknown"
		Other  = "ERROR";

* SUB-SECTOR ;
		***format for allocating providers to the CURRENT sub-sector when calculating graduate outcomes using IDI;
	value ssnid_idi
		6002,6023,6501,6503,6504,6505,6506,7001-7008="1"
		6001,6003-6021,6022,6024,8505				="2"
		8630,9241,9386								="4"
		other										="6";

		***format for allocating providers to the CURRENT sub-sector;
	value ssnid
		6002,6023,6501,6503,6504,7001-7008			="1"
		6001,6003-6021,6022,6024,8505				="2"
		6505,6506									="3"
		8630,9241,9386								="4"
		8502,8503,8504,8510,9043,
		9086,9087,9088,9381,9520,9605				="5" 	  
		other										="6";   

		***format for allocating providers to their ORIGINAL sub-sector;
	value ssid
		7001-7008									="1"
		6001-6024,8505								="2"
		6501,6503,6504,6505,6506					="3"
		8630,9241,9386								="4"
		8502,8503,8504,8510,8809,9043,
		9086,9087,9088,9381,9508,9520,9605			="5" 	  
		other										="6";   

		***labels for standard grouping;
	value $ss
		"1"	=	"Universities"
		"2"	=	"Institutes of technology and polytechnics"
		"3"	=	"Colleges of education"
		"4"	=	"Wananga"
		"5"	=	"OTEPs"
		"6"	=	"Private training establishments"
		"T"  =	"Total students" ; 

		*** labels for higher groupings ;
	value $ssgp_a
		"1" =	"Universities"
		"2"	=	"Institutes of Technology and Polytechnics"
		"3"	=	"Colleges of Education"
		"4"	=	"Wananga"
		"5", "6" = "Private Training Establishments";

	
	***labels for institutions;
	value $ssgp
		"1"	=	"Universities"
		"2"	=	"Institutes of technology and polytechnics"
		"3"	=	"Colleges of education"
		"4"	=	"Wananga"
		"5"	=	"Public providers"
		"6"	=	"Private training establishments"
		"T"  =	"Total students" ; 

	***format for allocating sub-sectors to whether public or private;
	value $gp
		"5"-"6"		=	"PTEs"
		 other		=	"TEIs";

* WEEKS ;
	***standard grouping of weeks: sort order ids;
	value wlid
		0-<12	=	"1"
		12-<24	=	"2"
		24-<32	=	"3"
		32-high	=	"4"
		other 	=	"9";

	***standard grouping of weeks: labels;
	value $wl
		"1"	=	"0 -12 weeks"
		"2"	=	"12-23 weeks"
		"3"	=	"24-31 weeks"
		"4"	=	"32-52 weeks"
		"9"	=   "Unknown";

	run;
